import type { AppLocale } from "./app-locale";
import { createLocaleCopyMap, type DeepPartial } from "./copy-helpers";

/**
 * i18n copy for Career Vault Phase 5 — Command Center dashboard, Timeline,
 * Network graph, Analytics, Journal, Profile and Omnisearch. English is the
 * source of truth; missing locale overrides fall back to English via the
 * shared copy-helpers merge logic (see `createLocaleCopyMap`).
 */
export type CareerPhase5Copy = {
  dashboard: {
    pageTitle: string;
    pageDescription: string;
    sections: {
      today: string;
      atAGlance: string;
      thisWeek: string;
      intelligence: string;
      submenus: string;
    };
    today: {
      transitionProgress: string;
      topGoal: string;
      nextAction: string;
      notSetYet: string;
      noUpcoming: string;
      profileIncomplete: (pct: number) => string;
      profileCta: string;
      transitionCta: string;
    };
    stats: {
      files: string;
      activeApps: string;
      offers: string;
      contacts: string;
      decisions: string;
      events: string;
    };
    upcoming: {
      title: string;
      empty: string;
      interviewSoon: string;
      followUp: string;
      dueToday: string;
    };
    intelligence: {
      hotInterviews: (n: number) => string;
      coldContacts: (n: number) => string;
      skillsGap: (skills: string) => string;
      noSkillsGap: string;
      aiSuggestion: string;
      aiLoading: string;
      aiEmpty: string;
      aiRegenerate: string;
      markDone: string;
      dismiss: string;
      priority: { high: string; medium: string; low: string };
      category: {
        application: string;
        skill: string;
        network: string;
        reflection: string;
      };
    };
    submenu: {
      compass: string;
      profile: string;
      coach: string;
      vault: string;
      pipeline: string;
      timeline: string;
      network: string;
      journal: string;
      analytics: string;
    };
  };

  timeline: {
    pageTitle: string;
    pageDescription: string;
    filters: {
      all: string;
      education: string;
      jobs: string;
      files: string;
      events: string;
      shares: string;
      opportunities: string;
    };
    viewModes: { year: string; decade: string; all: string };
    empty: string;
    newEvent: string;
    editEvent: string;
    deleteEvent: string;
    confirmDelete: string;
    autoGenerated: string;
    relatedFiles: string;
    eventTypes: Record<string, string>;
    form: {
      title: string;
      description: string;
      eventType: string;
      startDate: string;
      endDate: string;
      isOngoing: string;
      organization: string;
      location: string;
      relatedFiles: string;
      save: string;
      cancel: string;
      titleRequired: string;
    };
  };

  network: {
    pageTitle: string;
    pageDescription: string;
    filters: {
      all: string;
      people: string;
      organizations: string;
      projects: string;
      opportunities: string;
    };
    empty: string;
    youNode: string;
    addNode: string;
    addEdge: string;
    warmth: {
      hot: string;
      warm: string;
      cooling: string;
      cold: string;
      unknown: string;
    };
    stats: {
      total: string;
      hot: string;
      needReconnect: string;
    };
    suggestions: {
      heading: string;
      reconnect: (name: string, days: number) => string;
      connectToOpp: (name: string, company: string) => string;
    };
    detail: {
      notes: string;
      lastInteraction: string;
      logInteraction: string;
      setReminder: string;
      draftReconnect: string;
      relatedOpportunities: string;
      delete: string;
      save: string;
      cancel: string;
      linkedinUrl: string;
      email: string;
      roleTitle: string;
      website: string;
      projectUrl: string;
    };
    form: {
      nodeType: string;
      name: string;
      subtitle: string;
      description: string;
      tags: string;
      tagsHint: string;
      nodeTypes: Record<string, string>;
      edgeType: string;
      edgeTypeHint: string;
      strength: string;
      save: string;
      cancel: string;
    };
  };

  analytics: {
    pageTitle: string;
    pageDescription: string;
    funnel: {
      title: string;
      stages: Record<string, string>;
      empty: string;
    };
    responseRates: {
      title: string;
      description: string;
      empty: string;
      version: string;
      applications: string;
      interviews: string;
      rate: string;
    };
    fileBreakdown: {
      title: string;
      empty: string;
    };
    interactionsOverTime: {
      title: string;
      description: string;
    };
    stageTime: {
      title: string;
      description: string;
      days: (n: number) => string;
    };
    report: {
      quarterlyTitle: string;
      quarterlyDescription: string;
      generate: string;
      generating: string;
      download: string;
      currentQuarter: (label: string) => string;
    };
  };

  journal: {
    pageTitle: string;
    pageDescription: string;
    newDecision: string;
    empty: string;
    decidedOn: (date: string) => string;
    reviewDue: (date: string) => string;
    reviewNow: string;
    qualityScore: (score: number) => string;
    trendTitle: string;
    trendEmpty: string;
    frameworks: {
      pros_cons: string;
      "10_10_10": string;
      regret_minimization: string;
      expected_value: string;
      custom: string;
    };
    frameworkDescriptions: {
      pros_cons: string;
      "10_10_10": string;
      regret_minimization: string;
      expected_value: string;
      custom: string;
    };
    decisionTypes: Record<string, string>;
    form: {
      title: string;
      decisionType: string;
      framework: string;
      context: string;
      contextHint: string;
      options: string;
      addOption: string;
      optionName: string;
      pros: string;
      cons: string;
      score: string;
      scoreHint: string;
      assumptions: string;
      decision: string;
      expectedOutcome: string;
      decidedAt: string;
      reviewReminder: string;
      save: string;
      cancel: string;
      remove: string;
    };
    review: {
      heading: string;
      actualOutcome: string;
      lessonsLearned: string;
      qualityScore: string;
      qualityHint: string;
      save: string;
    };
  };

  profile: {
    pageTitle: string;
    pageDescription: string;
    completeness: (pct: number) => string;
    sections: {
      basics: string;
      narrative: string;
      targets: string;
      compensation: string;
      linkedAssets: string;
      transition: string;
    };
    fields: {
      currentRole: string;
      currentCompany: string;
      industry: string;
      location: string;
      yearsExperience: string;
      topSkills: string;
      highlights: string;
      addHighlight: string;
      careerGoals: string;
      twelveMonthGoals: string;
      dreamScenario: string;
      painPoints: string;
      blockers: string;
      targetRoles: string;
      targetIndustries: string;
      targetLocations: string;
      salaryMin: string;
      salaryMax: string;
      currency: string;
      headshot: string;
      bio: string;
      masterResume: string;
      transitionGoal: string;
      transitionProgress: string;
    };
    placeholders: {
      csv: string;
      highlightTitle: string;
      highlightDescription: string;
      highlightYear: string;
    };
    linked: {
      selectFromVault: string;
      clear: string;
      notSet: string;
      filter: (label: string) => string;
    };
    save: string;
    saving: string;
  };

  omnisearch: {
    trigger: string;
    placeholder: string;
    noResults: string;
    groups: {
      files: string;
      opportunities: string;
      contacts: string;
      events: string;
      prompts: string;
      customPrompts: string;
      decisions: string;
      quickActions: string;
    };
    quickActions: {
      newOpportunity: string;
      newEvent: string;
      newDecision: string;
      newContact: string;
      openDashboard: string;
      openTimeline: string;
      openNetwork: string;
      openAnalytics: string;
    };
  };

  autoEvents: {
    newMasterResume: (name: string) => string;
    jobOfferAccepted: (company: string) => string;
    gradSchoolSubmitted: (name: string) => string;
  };
};

const en: CareerPhase5Copy = {
  dashboard: {
    pageTitle: "Career Command Center",
    pageDescription:
      "Your transition at a glance — signals, actions, and the people around them.",
    sections: {
      today: "You today",
      atAGlance: "At a glance",
      thisWeek: "This week",
      intelligence: "Intelligence",
      submenus: "Submenus",
    },
    today: {
      transitionProgress: "Transition progress",
      topGoal: "Top goal",
      nextAction: "Next action",
      notSetYet: "Not set yet",
      noUpcoming: "Nothing scheduled",
      profileIncomplete: (pct) =>
        `Your profile is ${pct}% complete — finish it to unlock richer coaching.`,
      profileCta: "Finish profile",
      transitionCta: "Set a goal",
    },
    stats: {
      files: "Files",
      activeApps: "Active apps",
      offers: "Offers",
      contacts: "Contacts",
      decisions: "Decisions",
      events: "Events",
    },
    upcoming: {
      title: "This week",
      empty: "Your week is clear. Plan a small move.",
      interviewSoon: "Interview",
      followUp: "Follow-up",
      dueToday: "Due today",
    },
    intelligence: {
      hotInterviews: (n) => `${n} active interview${n === 1 ? "" : "s"}`,
      coldContacts: (n) =>
        `${n} contact${n === 1 ? "" : "s"} need a quick check-in`,
      skillsGap: (skills) => `Missing across your pipeline: ${skills}`,
      noSkillsGap: "No recurring skill gaps yet",
      aiSuggestion: "Daily suggestions",
      aiLoading: "Thinking through your week…",
      aiEmpty: "No suggestions yet — they refresh once daily.",
      aiRegenerate: "Regenerate",
      markDone: "Mark done",
      dismiss: "Dismiss",
      priority: { high: "High", medium: "Medium", low: "Low" },
      category: {
        application: "Application",
        skill: "Skill",
        network: "Network",
        reflection: "Reflection",
      },
    },
    submenu: {
      compass: "Compass",
      profile: "Profile",
      coach: "Coach",
      vault: "Vault",
      pipeline: "Pipeline",
      timeline: "Timeline",
      network: "Network",
      journal: "Journal",
      analytics: "Analytics",
    },
  },

  timeline: {
    pageTitle: "Career Timeline",
    pageDescription:
      "Everything that happened to your career, in one thread.",
    filters: {
      all: "All",
      education: "Education",
      jobs: "Jobs",
      files: "Files",
      events: "Events",
      shares: "Shares",
      opportunities: "Opportunities",
    },
    viewModes: { year: "Year", decade: "Decade", all: "All time" },
    empty: "No events yet. Add your first milestone to see it here.",
    newEvent: "New event",
    editEvent: "Edit",
    deleteEvent: "Delete",
    confirmDelete: "Delete this event? This can't be undone.",
    autoGenerated: "Auto-generated",
    relatedFiles: "Related files",
    eventTypes: {
      job_started: "Job started",
      job_ended: "Job ended",
      promotion: "Promotion",
      education_started: "Education started",
      education_completed: "Education completed",
      certification_earned: "Certification",
      project_shipped: "Project shipped",
      award_received: "Award",
      speaking_event: "Speaking event",
      publication: "Publication",
      milestone: "Milestone",
      custom: "Custom",
    },
    form: {
      title: "Title",
      description: "Description",
      eventType: "Event type",
      startDate: "Start date",
      endDate: "End date",
      isOngoing: "Still ongoing",
      organization: "Organization",
      location: "Location",
      relatedFiles: "Related vault files",
      save: "Save event",
      cancel: "Cancel",
      titleRequired: "Give this event a title.",
    },
  },

  network: {
    pageTitle: "Career Network",
    pageDescription: "Your people, places, and moving pieces — in one map.",
    filters: {
      all: "All",
      people: "People",
      organizations: "Orgs",
      projects: "Projects",
      opportunities: "Opportunities",
    },
    empty: "Your network is empty. Add the first person or organization.",
    youNode: "You",
    addNode: "Add node",
    addEdge: "Add connection",
    warmth: {
      hot: "Hot",
      warm: "Warm",
      cooling: "Cooling",
      cold: "Cold",
      unknown: "No contact yet",
    },
    stats: {
      total: "Nodes",
      hot: "Hot contacts",
      needReconnect: "Rekindle soon",
    },
    suggestions: {
      heading: "Suggestions",
      reconnect: (name, days) =>
        `You haven't talked to ${name} in ${days} days — send a quick check-in.`,
      connectToOpp: (name, company) =>
        `Connect ${name} to your ${company} opportunity.`,
    },
    detail: {
      notes: "Notes",
      lastInteraction: "Last interaction",
      logInteraction: "Log interaction",
      setReminder: "Set reminder",
      draftReconnect: "Draft reconnect message",
      relatedOpportunities: "Related opportunities",
      delete: "Delete node",
      save: "Save",
      cancel: "Cancel",
      linkedinUrl: "LinkedIn",
      email: "Email",
      roleTitle: "Role",
      website: "Website",
      projectUrl: "Project URL",
    },
    form: {
      nodeType: "Type",
      name: "Name",
      subtitle: "Subtitle",
      description: "Description",
      tags: "Tags",
      tagsHint: "Comma-separated, up to 10.",
      nodeTypes: {
        person: "Person",
        organization: "Organization",
        project: "Project",
        opportunity: "Opportunity",
      },
      edgeType: "Relationship",
      edgeTypeHint: "e.g. mentor, peer, reference, works_at, attended",
      strength: "Strength (1–5)",
      save: "Save",
      cancel: "Cancel",
    },
  },

  analytics: {
    pageTitle: "Career Analytics",
    pageDescription: "Signal from the noise of your job search.",
    funnel: {
      title: "Application funnel",
      stages: {
        researching: "Researching",
        applied: "Applied",
        phone_screen: "Phone screen",
        interviewing: "Interview",
        offer: "Offer",
        accepted: "Accepted",
        rejected: "Rejected",
        withdrawn: "Withdrawn",
      },
      empty: "No opportunities tracked yet.",
    },
    responseRates: {
      title: "Resume response rates",
      description:
        "Interview conversion by which resume version was attached.",
      empty: "Attach resumes to opportunities to see rates here.",
      version: "Resume",
      applications: "Applications",
      interviews: "Interviews",
      rate: "Rate",
    },
    fileBreakdown: {
      title: "Files by category",
      empty: "Upload files to see your vault breakdown.",
    },
    interactionsOverTime: {
      title: "Interactions over time",
      description: "Touchpoints across your network, last 12 weeks.",
    },
    stageTime: {
      title: "Time in pipeline stage",
      description: "Median days spent in each stage before moving on.",
      days: (n) => `${n}d`,
    },
    report: {
      quarterlyTitle: "Quarterly report",
      quarterlyDescription:
        "Download a PDF snapshot of your wins, learnings, and focus.",
      generate: "Generate quarterly report",
      generating: "Generating…",
      download: "Download PDF",
      currentQuarter: (label) => `Generate ${label} report`,
    },
  },

  journal: {
    pageTitle: "Decision Journal",
    pageDescription:
      "Make the call, write it down, review it later. Get better at deciding.",
    newDecision: "New decision",
    empty: "No decisions yet. Start one the next time you're weighing a move.",
    decidedOn: (date) => `Decided ${date}`,
    reviewDue: (date) => `Review due ${date}`,
    reviewNow: "Review now",
    qualityScore: (score) => `Quality ${score}/10`,
    trendTitle: "Decision quality trend",
    trendEmpty: "Complete reviews to see your quality trend.",
    frameworks: {
      pros_cons: "Pros & Cons",
      "10_10_10": "10/10/10",
      regret_minimization: "Regret minimization",
      expected_value: "Expected value",
      custom: "Custom",
    },
    frameworkDescriptions: {
      pros_cons: "List the upsides and downsides of each option.",
      "10_10_10":
        "How will you feel in 10 minutes, 10 months, and 10 years from now?",
      regret_minimization:
        "Which choice minimizes future regret at age 80?",
      expected_value:
        "Assign probabilities and magnitudes to each outcome.",
      custom: "Write a free-form analysis of your own.",
    },
    decisionTypes: {
      job_offer: "Job offer",
      career_pivot: "Career pivot",
      education: "Education",
      relocation: "Relocation",
      side_project: "Side project",
      mentor_choice: "Mentor",
      investment: "Investment",
      custom: "Custom",
    },
    form: {
      title: "Title",
      decisionType: "Decision type",
      framework: "Framework",
      context: "Context",
      contextHint: "What situation are you deciding within?",
      options: "Options",
      addOption: "Add option",
      optionName: "Option",
      pros: "Pros",
      cons: "Cons",
      score: "Score",
      scoreHint: "Personal rating 1–10.",
      assumptions: "Assumptions",
      decision: "What you decided",
      expectedOutcome: "Expected outcome",
      decidedAt: "Decided on",
      reviewReminder: "Review on",
      save: "Save decision",
      cancel: "Cancel",
      remove: "Remove",
    },
    review: {
      heading: "Review",
      actualOutcome: "Actual outcome",
      lessonsLearned: "Lessons learned",
      qualityScore: "How good was this decision? (1–10)",
      qualityHint:
        "Score the decision process, not the outcome — good decisions can have bad outcomes.",
      save: "Save review",
    },
  },

  profile: {
    pageTitle: "My Career Profile",
    pageDescription:
      "Single source of truth for the AI Coach, Command Center, and prompts.",
    completeness: (pct) => `Profile ${pct}% complete`,
    sections: {
      basics: "Basics",
      narrative: "Career narrative",
      targets: "Targets",
      compensation: "Compensation",
      linkedAssets: "Linked assets",
      transition: "Transition goal",
    },
    fields: {
      currentRole: "Current role",
      currentCompany: "Current company",
      industry: "Industry",
      location: "Location",
      yearsExperience: "Years of experience",
      topSkills: "Top skills",
      highlights: "Career highlights",
      addHighlight: "Add highlight",
      careerGoals: "Career goals",
      twelveMonthGoals: "12-month goals",
      dreamScenario: "Dream scenario",
      painPoints: "Pain points",
      blockers: "Blockers",
      targetRoles: "Target roles",
      targetIndustries: "Target industries",
      targetLocations: "Target locations",
      salaryMin: "Salary min",
      salaryMax: "Salary max",
      currency: "Currency",
      headshot: "Primary headshot",
      bio: "Primary bio",
      masterResume: "Master resume",
      transitionGoal: "Transition goal",
      transitionProgress: "Transition progress",
    },
    placeholders: {
      csv: "Comma-separated values",
      highlightTitle: "Shipped v1 of MLOS",
      highlightDescription: "Led a 4-person team and launched on App Store",
      highlightYear: "2026",
    },
    linked: {
      selectFromVault: "Select from vault",
      clear: "Clear",
      notSet: "Not set",
      filter: (label) => `Filter to ${label}`,
    },
    save: "Save profile",
    saving: "Saving…",
  },

  omnisearch: {
    trigger: "Search everything (⌘K)",
    placeholder: "Search files, contacts, opportunities…",
    noResults: "No results.",
    groups: {
      files: "Files",
      opportunities: "Opportunities",
      contacts: "Contacts",
      events: "Timeline",
      prompts: "Prompts",
      customPrompts: "Custom prompts",
      decisions: "Decisions",
      quickActions: "Quick actions",
    },
    quickActions: {
      newOpportunity: "New opportunity",
      newEvent: "New timeline event",
      newDecision: "New decision",
      newContact: "New contact",
      openDashboard: "Open Command Center",
      openTimeline: "Open Timeline",
      openNetwork: "Open Network",
      openAnalytics: "Open Analytics",
    },
  },

  autoEvents: {
    newMasterResume: (name) => `New master resume: ${name}`,
    jobOfferAccepted: (company) => `Job offer accepted: ${company}`,
    gradSchoolSubmitted: (name) => `Grad school application: ${name}`,
  },
};

const overrides: Partial<Record<AppLocale, DeepPartial<CareerPhase5Copy>>> = {
  "zh-TW": {
    dashboard: {
      pageTitle: "職涯指揮中心",
      pageDescription: "一眼看完轉型現況：訊號、行動、與背後的人際網絡。",
      sections: {
        today: "今天的你",
        atAGlance: "概覽",
        thisWeek: "本週",
        intelligence: "智慧提醒",
        submenus: "子選單",
      },
      today: {
        transitionProgress: "轉型進度",
        topGoal: "首要目標",
        nextAction: "下一步行動",
        notSetYet: "尚未設定",
        noUpcoming: "近期無待辦",
        profileIncomplete: (pct) =>
          `檔案已完成 ${pct}%，補齊後 AI Coach 會更精準。`,
        profileCta: "完成檔案",
        transitionCta: "設定目標",
      },
      submenu: {
        compass: "指南針",
        profile: "檔案",
        coach: "教練",
        vault: "文件庫",
        pipeline: "機會管線",
        timeline: "時間軸",
        network: "人脈圖",
        journal: "決策日誌",
        analytics: "數據分析",
      },
    },
    timeline: { pageTitle: "職涯時間軸", newEvent: "新增事件" },
    network: { pageTitle: "職涯人脈圖", addNode: "新增節點" },
    analytics: { pageTitle: "職涯分析" },
    journal: { pageTitle: "決策日誌", newDecision: "新增決策" },
    profile: { pageTitle: "我的職涯檔案", save: "儲存", saving: "儲存中…" },
    omnisearch: { trigger: "全站搜尋（⌘K）", placeholder: "搜尋檔案、聯絡人、機會…" },
  },
  "zh-CN": {
    dashboard: {
      pageTitle: "职业指挥中心",
      pageDescription: "一眼看懂你的转型：信号、行动、背后的人。",
      submenu: {
        compass: "指南针",
        profile: "资料",
        coach: "教练",
        vault: "文件库",
        pipeline: "机会管线",
        timeline: "时间轴",
        network: "人脉图",
        journal: "决策日志",
        analytics: "数据分析",
      },
    },
    timeline: { pageTitle: "职业时间轴" },
    network: { pageTitle: "职业人脉图" },
    analytics: { pageTitle: "职业分析" },
    journal: { pageTitle: "决策日志" },
    profile: { pageTitle: "我的职业资料" },
    omnisearch: { trigger: "全站搜索（⌘K）" },
  },
  ja: {
    dashboard: {
      pageTitle: "キャリアコマンドセンター",
      submenu: {
        compass: "コンパス",
        profile: "プロフィール",
        coach: "コーチ",
        vault: "ボールト",
        pipeline: "パイプライン",
        timeline: "タイムライン",
        network: "ネットワーク",
        journal: "意思決定ログ",
        analytics: "分析",
      },
    },
    timeline: { pageTitle: "キャリアタイムライン" },
    network: { pageTitle: "キャリアネットワーク" },
    analytics: { pageTitle: "キャリア分析" },
    journal: { pageTitle: "意思決定ログ" },
    profile: { pageTitle: "マイキャリアプロフィール" },
  },
  ko: {
    dashboard: { pageTitle: "커리어 커맨드 센터" },
    timeline: { pageTitle: "커리어 타임라인" },
    network: { pageTitle: "커리어 네트워크" },
    analytics: { pageTitle: "커리어 분석" },
    journal: { pageTitle: "의사결정 저널" },
    profile: { pageTitle: "나의 커리어 프로필" },
  },
  fr: {
    dashboard: { pageTitle: "Centre de commande carrière" },
    timeline: { pageTitle: "Chronologie de carrière" },
    network: { pageTitle: "Réseau professionnel" },
    analytics: { pageTitle: "Analyse de carrière" },
    journal: { pageTitle: "Journal de décisions" },
    profile: { pageTitle: "Mon profil carrière" },
  },
  it: {
    dashboard: { pageTitle: "Centro di comando carriera" },
    timeline: { pageTitle: "Timeline della carriera" },
    network: { pageTitle: "Rete professionale" },
    analytics: { pageTitle: "Analisi carriera" },
    journal: { pageTitle: "Diario delle decisioni" },
    profile: { pageTitle: "Il mio profilo carriera" },
  },
  es: {
    dashboard: { pageTitle: "Centro de mando profesional" },
    timeline: { pageTitle: "Línea de tiempo profesional" },
    network: { pageTitle: "Red profesional" },
    analytics: { pageTitle: "Análisis profesional" },
    journal: { pageTitle: "Diario de decisiones" },
    profile: { pageTitle: "Mi perfil profesional" },
  },
  vi: {
    dashboard: { pageTitle: "Trung tâm chỉ huy sự nghiệp" },
    timeline: { pageTitle: "Dòng thời gian sự nghiệp" },
    network: { pageTitle: "Mạng lưới sự nghiệp" },
    analytics: { pageTitle: "Phân tích sự nghiệp" },
    journal: { pageTitle: "Nhật ký quyết định" },
    profile: { pageTitle: "Hồ sơ sự nghiệp của tôi" },
  },
};

const COPY_MAP = createLocaleCopyMap<CareerPhase5Copy>(en, overrides);

export function getCareerPhase5Copy(locale: AppLocale): CareerPhase5Copy {
  return COPY_MAP[locale];
}
