const en = {
  leaveUnsaved: "This room is not in Saved rooms yet. Close without saving?",
  create: "Create Council", saved: "Saved rooms", library: "Advisor library", question: "What would you like to think through?",
  intro: "Bring one question. Choose 2–4 perspectives. Think it through together.",
  placeholder: "What decision, idea or challenge is on your mind?", recommend: "Recommend advisors", recommending: "Finding your advisors…",
  choose: "Choose advisors", recommended: "Recommended for your question", chosen: "selected", run: "Run Council", creating: "Opening your room…",
  name: "Council name", save: "Save room", savedLabel: "Saved", saveName: "Save name", close: "Close room", edit: "Rename",
  emptySaved: "Your saved Council rooms will appear here.", loadMore: "Load more", loading: "Loading…", open: "Open room",
  emptyChat: "Your Council is ready. Ask a question or @mention an advisor.",
  composer: "Ask your Council. Type @ to choose who replies…", send: "Send", stop: "Stop", retry: "Retry unfinished replies",
  everyone: "Everyone", replyingTo: "Replying to", exchange: "Let advisors respond to one another", exchangeHint: "Two rounds, then a short summary. Turn off for one round.",
  typing: "You are typing", thinking: "Preparing a reply", round: "Round", you: "You", summary: "Council summary",
  sceneLoading: "Creating your Council room…", sceneHint: "Your selected advisors are being placed in the scene. You can chat while it loads.",
  sceneRetry: "Retry scene", sceneFailed: "Scene unavailable. Your conversation is still here.",
  sceneTap: "Tap an advisor’s profile to @mention them.", hideRoom: "Hide scene", showRoom: "Show scene", aiScene: "AI-generated scene",
  disclaimer: "AI-simulated perspectives inspired by public ideas. Not the real people or their endorsements.",
  dataNotice: "Starting sends your question and selected perspectives to the AI service. Scene generation uses advisor names only, never your profile photo or conversation.",
  setting: "Room setting", surprise: "Surprise me", sunset: "Sunset library", garden: "Garden room", loft: "City loft", coast: "Coastal retreat",
  max: "Choose no more than 4 advisors.", error: "Something went wrong. Please try again.",
  interrupted: "The turn stopped before completion. Earlier replies are saved.", reconnect: "A reply is still being prepared in this room…",
  noScene: "A new scene will be generated for this room.", search: "Search advisors", start: "Question", assemble: "Advisors", room: "Council room",
};
export type RoomCopy = typeof en;
const zh: RoomCopy = {
  leaveUnsaved: "呢間房未加入已儲存房間。確定唔儲存就關閉？",
  create: "建立 Council", saved: "已儲存房間", library: "顧問資料庫", question: "你而家想諗清楚啲乜？",
  intro: "帶住一個問題，揀 2–4 位顧問，一齊深入討論。", placeholder: "寫低你面對嘅決定、想法或者挑戰…",
  recommend: "推薦顧問", recommending: "正在推薦顧問…", choose: "自行選擇", recommended: "為你嘅問題推薦", chosen: "位已選", run: "Run Council", creating: "正在開啟房間…",
  name: "Council 名稱", save: "儲存房間", savedLabel: "已儲存", saveName: "儲存名稱", close: "關閉房間", edit: "改名",
  emptySaved: "儲存後，你可以喺呢度重新開啟同一間房。", loadMore: "載入更多", loading: "載入中…", open: "開啟房間",
  emptyChat: "Council 已準備好。直接發問，或者 @ 指定顧問。", composer: "向 Council 發問，輸入 @ 選擇回覆對象…",
  send: "傳送", stop: "停止", retry: "重試未完成嘅回覆", everyone: "所有顧問", replyingTo: "回覆對象", exchange: "讓顧問互相回應",
  exchangeHint: "兩輪交流，再整理重點；關閉後只進行一輪。", typing: "你正在打字", thinking: "正在準備回覆", round: "回合", you: "你", summary: "Council 重點整理",
  sceneLoading: "正在生成你嘅 Council Room…", sceneHint: "正在將所選顧問加入場景；等待期間可以繼續聊天。",
  sceneRetry: "重試生成場景", sceneFailed: "場景暫時未能載入，對話仍然保留。", sceneTap: "點選顧問頭像，即可 @ 提問。",
  hideRoom: "隱藏場景", showRoom: "顯示場景", aiScene: "AI 生成場景", disclaimer: "AI 參考公開思想模擬視角，唔係人物本人回覆或認可。",
  dataNotice: "開始後會將問題及所選視角交予 AI 服務。生成場景只使用顧問名稱，唔會傳送你嘅頭像或對話內容。",
  setting: "房間場景", surprise: "隨機場景", sunset: "日落書房", garden: "庭園房間", loft: "城市 Loft", coast: "海邊別墅",
  max: "最多只可以揀 4 位顧問。", error: "操作未能完成，請再試一次。", interrupted: "今輪對話未完成，之前嘅回覆已保留。",
  reconnect: "房間內嘅回覆仍在準備中…", noScene: "呢間新房會生成專屬場景。", search: "搜尋顧問", start: "問題", assemble: "選擇顧問", room: "Council Room",
};
export const roomCopy = (locale: string): RoomCopy => locale.startsWith("zh") ? zh : en;
