import { createClient } from "@/lib/supabase/client";
import type {
  CareerEvent,
  CareerEventSourceKind,
  CareerEventType,
} from "@/types/database";

export type CreateEventInput = {
  eventType: CareerEventType;
  title: string;
  description?: string | null;
  startDate: string;
  endDate?: string | null;
  isOngoing?: boolean;
  organization?: string | null;
  location?: string | null;
  relatedFileIds?: string[];
  color?: string | null;
  icon?: string | null;
  autoGenerated?: boolean;
  sourceKind?: CareerEventSourceKind;
  sourceId?: string | null;
};

export type UpdateEventInput = Partial<{
  event_type: CareerEventType;
  title: string;
  description: string | null;
  start_date: string;
  end_date: string | null;
  is_ongoing: boolean;
  organization: string | null;
  location: string | null;
  related_file_ids: string[];
  color: string | null;
  icon: string | null;
}>;

export const careerEventsRepository = {
  async list(): Promise<CareerEvent[]> {
    const supabase = createClient();
    const { data, error } = await supabase
      .from("career_events")
      .select("*")
      .order("start_date", { ascending: false });
    if (error) throw error;
    return (data ?? []) as CareerEvent[];
  },

  async create(input: CreateEventInput): Promise<CareerEvent> {
    const supabase = createClient();
    const { data, error } = await supabase
      .from("career_events")
      .insert({
        event_type: input.eventType,
        title: input.title,
        description: input.description ?? null,
        start_date: input.startDate,
        end_date: input.endDate ?? null,
        is_ongoing: input.isOngoing ?? false,
        organization: input.organization ?? null,
        location: input.location ?? null,
        related_file_ids: input.relatedFileIds ?? [],
        color: input.color ?? null,
        icon: input.icon ?? null,
        auto_generated: input.autoGenerated ?? false,
        source_kind: input.sourceKind ?? null,
        source_id: input.sourceId ?? null,
      })
      .select()
      .single();
    if (error) throw error;
    return data as CareerEvent;
  },

  async update(id: string, updates: UpdateEventInput): Promise<CareerEvent> {
    const supabase = createClient();
    const { data, error } = await supabase
      .from("career_events")
      .update({ ...updates, updated_at: new Date().toISOString() })
      .eq("id", id)
      .select()
      .single();
    if (error) throw error;
    return data as CareerEvent;
  },

  async delete(id: string): Promise<void> {
    const supabase = createClient();
    const { error } = await supabase
      .from("career_events")
      .delete()
      .eq("id", id);
    if (error) throw error;
  },

  /**
   * Idempotent auto-event creator — used by hooks that should fire-and-forget
   * an event on key user actions. Skips silently if an event with the same
   * (source_kind, source_id) already exists to avoid double-emitting when a
   * mutation retries.
   */
  async upsertAutoEvent(input: CreateEventInput & {
    sourceKind: Exclude<CareerEventSourceKind, null>;
    sourceId: string;
  }): Promise<CareerEvent | null> {
    const supabase = createClient();
    const { data: existing } = await supabase
      .from("career_events")
      .select("id")
      .eq("source_kind", input.sourceKind)
      .eq("source_id", input.sourceId)
      .limit(1);
    if (existing && existing.length > 0) return null;
    return careerEventsRepository.create({ ...input, autoGenerated: true });
  },
};
