/**
 * Default seed taxonomy.
 *
 * This is the single source of truth for canonical tags, categories, and
 * aliases. It is intentionally hand-curated rather than auto-generated:
 *   1. Auto-generated taxonomies recreate the duplicate problem ("ai-agent"
 *      vs "ai-agents") because LLMs can't remember which canonical tag they
 *      created last week.
 *   2. A short curated set is good enough for the majority of items and
 *      everything that doesn't match falls into the synthetic `Other`
 *      category until a human (or future admin tool) promotes it.
 *
 * To add a new canonical tag: append a new `CanonicalTagDef` and include
 * every spelling variant the AI tagger has produced (or might produce) in
 * `aliases`. The matcher already handles case / hyphen / plural variants
 * automatically; aliases are for *semantic* synonyms only (different words
 * that mean the same concept, including bilingual forms).
 */

import type { CanonicalTagDef, TagCategoryDef } from "./types";

export const TAG_CATEGORIES: TagCategoryDef[] = [
  {
    id: "technology",
    name: "Technology",
    slug: "technology",
    description: "AI, software, hardware, and engineering",
    accent: "violet",
    iconName: "Cpu",
    order: 10,
  },
  {
    id: "business",
    name: "Business",
    slug: "business",
    description: "Branding, marketing, strategy, startups",
    accent: "amber",
    iconName: "Briefcase",
    order: 20,
  },
  {
    id: "design",
    name: "Design",
    slug: "design",
    description: "UI/UX, visual systems, product design",
    accent: "pink",
    iconName: "Palette",
    order: 30,
  },
  {
    id: "media",
    name: "Media & Content",
    slug: "media-content",
    description: "Social media, content creation, and video",
    accent: "orange",
    iconName: "Globe2",
    order: 40,
  },
  {
    id: "education",
    name: "Education",
    slug: "education",
    description: "Learning systems, pedagogy, student development",
    accent: "emerald",
    iconName: "GraduationCap",
    order: 50,
  },
  {
    id: "music",
    name: "Music & Arts",
    slug: "music-arts",
    description: "Performance, education, theory, festivals",
    accent: "rose",
    iconName: "Music",
    order: 60,
  },
  {
    id: "productivity",
    name: "Productivity",
    slug: "productivity",
    description: "Workflows, systems, and execution",
    accent: "indigo",
    iconName: "Sparkles",
    order: 70,
  },
  {
    id: "events",
    name: "Events",
    slug: "events",
    description: "Festivals, programs, workshops, and competitions",
    accent: "teal",
    iconName: "Layers",
    order: 80,
  },
  {
    id: "research",
    name: "Research",
    slug: "research",
    description: "Studies, analysis, reports, and academic work",
    accent: "blue",
    iconName: "Microscope",
    order: 90,
  },
  {
    id: "health",
    name: "Health",
    slug: "health",
    description: "Wellness, medicine, fitness, longevity",
    accent: "teal",
    iconName: "HeartPulse",
    order: 110,
  },
  {
    id: "science",
    name: "Science",
    slug: "science",
    description: "Research, biology, physics, neuroscience",
    accent: "blue",
    iconName: "Microscope",
    order: 120,
  },
  {
    id: "personal",
    name: "Personal Growth",
    slug: "personal-growth",
    description: "Productivity, habits, mindset, philosophy",
    accent: "indigo",
    iconName: "Sparkles",
    order: 130,
  },
  {
    id: "world",
    name: "World & Culture",
    slug: "world-culture",
    description: "Politics, society, travel, history",
    accent: "slate",
    iconName: "Globe2",
    order: 140,
  },
];

/**
 * Canonical tag tree. Order doesn't matter for runtime correctness, but
 * keeping siblings together makes diffs readable.
 *
 * Aliases: include EVERY observed messy variant. Casing, hyphen, plural,
 * and Latin/CJK punctuation forms are handled by the normalizer — but
 * cross-language synonyms (`ai 代理` ⇒ `ai-agents`) MUST be listed.
 */
export const CANONICAL_TAGS: CanonicalTagDef[] = [
  // ── Technology ────────────────────────────────────────────────────────
  {
    id: "ai",
    name: "AI",
    slug: "ai",
    description: "Artificial intelligence in general",
    parentId: null,
    categoryId: "technology",
    type: "concept",
    aliases: [
      "artificial intelligence",
      "machine intelligence",
      "ai general",
      "人工智能",
      "人工智慧",
      "ai 一般",
    ],
  },
  {
    id: "ai-agents",
    name: "AI Agents",
    slug: "ai-agents",
    description: "Autonomous LLM agents and agentic systems",
    parentId: "ai",
    categoryId: "technology",
    type: "concept",
    aliases: [
      "agent",
      "agents",
      "ai agent",
      "agentic",
      "agentic ai",
      "agentic systems",
      "autonomous agents",
      "llm agent",
      "llm agents",
      "ai 代理",
      "ai 代理人",
      "agent skill",
      "智能代理",
    ],
  },
  {
    id: "agent-skills",
    name: "Agent Skills",
    slug: "agent-skills",
    description: "Capabilities, skills, tool-use for agents",
    parentId: "ai-agents",
    categoryId: "technology",
    type: "method",
    aliases: ["skill", "skills", "agent capability", "agent capabilities", "agent tool use"],
  },
  {
    id: "ai-workflows",
    name: "AI Workflows",
    slug: "ai-workflows",
    description: "Multi-step AI orchestration and pipelines",
    parentId: "ai-agents",
    categoryId: "technology",
    type: "method",
    aliases: [
      "ai workflow",
      "agent workflow",
      "agent workflows",
      "ai pipeline",
      "ai pipelines",
      "llm workflow",
      "llm workflows",
    ],
  },
  {
    id: "multi-agent-systems",
    name: "Multi-Agent Systems",
    slug: "multi-agent-systems",
    description: "Coordinated agent swarms and orchestration",
    parentId: "ai-agents",
    categoryId: "technology",
    type: "concept",
    aliases: [
      "multi agent",
      "multiagent",
      "multi-agent",
      "agent swarm",
      "agent swarms",
      "agent orchestration",
    ],
  },
  {
    id: "ai-deployment",
    name: "AI Deployment",
    slug: "ai-deployment",
    description: "Shipping, hosting, and operating AI systems",
    parentId: "ai-agents",
    categoryId: "technology",
    type: "method",
    aliases: [
      "ai ops",
      "ai-ops",
      "mlops",
      "llm deployment",
      "llm ops",
      "agent deployment",
      "production ai",
    ],
  },
  {
    id: "ai-tools",
    name: "AI Tools",
    slug: "ai-tools",
    description: "Tools, products, and platforms powered by AI",
    parentId: "ai",
    categoryId: "technology",
    type: "tool",
    aliases: [
      "ai tool",
      "ai-tool",
      "ai products",
      "ai product",
      "ai stack",
      "ai-stack",
      "ai 工具",
      "ai 应用",
      "llm tools",
    ],
  },
  {
    id: "ai-code-editors",
    name: "AI Code Editors",
    slug: "ai-code-editors",
    description: "Cursor, Copilot, Windsurf, and similar IDE assistants",
    parentId: "ai-tools",
    categoryId: "technology",
    type: "tool",
    aliases: [
      "ai ide",
      "ai-ide",
      "cursor",
      "github copilot",
      "copilot",
      "windsurf",
      "claude code",
      "ai coding",
      "ai code editor",
      "code assistant",
    ],
  },
  {
    id: "ai-automation",
    name: "AI Automation",
    slug: "ai-automation",
    description: "Workflow automation and RPA powered by AI",
    parentId: "ai-tools",
    categoryId: "technology",
    type: "method",
    aliases: [
      "automation",
      "automations",
      "n8n",
      "zapier",
      "make.com",
      "rpa",
      "ai workflow automation",
    ],
  },
  {
    id: "ai-video-generation",
    name: "AI Video Generation",
    slug: "ai-video-generation",
    description: "Text-to-video, video synthesis, motion models",
    parentId: "ai-tools",
    categoryId: "technology",
    type: "tool",
    aliases: [
      "video generation",
      "text to video",
      "text-to-video",
      "ai video",
      "ai-video",
      "sora",
      "runway",
      "veo",
      "kling",
    ],
  },
  {
    id: "ai-image-generation",
    name: "AI Image Generation",
    slug: "ai-image-generation",
    description: "Text-to-image and diffusion models",
    parentId: "ai-tools",
    categoryId: "technology",
    type: "tool",
    aliases: [
      "image generation",
      "text to image",
      "text-to-image",
      "midjourney",
      "stable diffusion",
      "dall-e",
      "dalle",
      "flux",
      "ideogram",
    ],
  },
  {
    id: "llms",
    name: "LLMs",
    slug: "llms",
    description: "Large language models",
    parentId: "ai",
    categoryId: "technology",
    type: "concept",
    aliases: [
      "llm",
      "large language model",
      "large language models",
      "language model",
      "language models",
      "gpt",
      "claude",
      "gemini",
      "llama",
      "大语言模型",
    ],
  },
  {
    id: "prompt-engineering",
    name: "Prompt Engineering",
    slug: "prompt-engineering",
    description: "Prompting techniques, system prompts, evals",
    parentId: "llms",
    categoryId: "technology",
    type: "method",
    aliases: [
      "prompting",
      "prompt design",
      "prompt-engineering",
      "system prompt",
      "system prompts",
      "prompt eval",
      "prompt evals",
    ],
  },
  {
    id: "rag",
    name: "RAG",
    slug: "rag",
    description: "Retrieval-augmented generation and embeddings",
    parentId: "llms",
    categoryId: "technology",
    type: "method",
    aliases: [
      "retrieval augmented generation",
      "retrieval-augmented generation",
      "vector search",
      "embeddings",
      "vector database",
      "vector db",
    ],
  },
  {
    id: "robotics",
    name: "Robotics",
    slug: "robotics",
    description: "Robots, embodied AI, hardware automation",
    parentId: null,
    categoryId: "technology",
    type: "concept",
    aliases: ["robot", "robots", "embodied ai", "humanoid robot", "humanoid robots", "机器人"],
  },
  {
    id: "robotics-xai",
    name: "xAI",
    slug: "xai-robotics",
    description: "xAI / Optimus and related work",
    parentId: "robotics",
    categoryId: "technology",
    type: "entity",
    aliases: ["xai", "optimus", "tesla bot", "tesla optimus"],
  },
  {
    id: "robotics-unitree",
    name: "Unitree",
    slug: "unitree",
    description: "Unitree Robotics and its product line",
    parentId: "robotics",
    categoryId: "technology",
    type: "entity",
    aliases: ["unitree robotics", "g1", "h1", "unitree g1", "unitree h1", "宇树"],
  },
  {
    id: "unitree-innovation",
    name: "Innovation",
    slug: "unitree-innovation",
    description: "Innovation themes around Unitree's product strategy",
    parentId: "robotics-unitree",
    categoryId: "technology",
    type: "topic",
    aliases: ["unitree innovation", "robotics innovation"],
  },
  {
    id: "web-dev",
    name: "Web Development",
    slug: "web-development",
    description: "Frontend, backend, full-stack engineering",
    parentId: null,
    categoryId: "technology",
    type: "concept",
    aliases: [
      "web dev",
      "web-dev",
      "frontend",
      "front-end",
      "front end",
      "backend",
      "back-end",
      "back end",
      "fullstack",
      "full-stack",
      "full stack",
      "javascript",
      "typescript",
    ],
  },
  {
    id: "frontend-tools",
    name: "Frontend Tools",
    slug: "frontend-tools",
    description: "React, Next.js, Tailwind, build tools",
    parentId: "web-dev",
    categoryId: "technology",
    type: "tool",
    aliases: [
      "react",
      "next.js",
      "nextjs",
      "next js",
      "tailwind",
      "tailwindcss",
      "vite",
      "shadcn",
      "shadcn/ui",
      "frontend tooling",
    ],
  },
  {
    id: "ui-systems",
    name: "UI Systems",
    slug: "ui-systems",
    description: "Design systems, component libraries, tokens",
    parentId: "web-dev",
    categoryId: "design",
    type: "concept",
    aliases: ["design system", "design systems", "component library", "component libraries", "ui kit"],
  },
  {
    id: "databases",
    name: "Databases",
    slug: "databases",
    description: "SQL, NoSQL, schema, ORMs",
    parentId: null,
    categoryId: "technology",
    type: "concept",
    aliases: [
      "database",
      "db",
      "sql",
      "postgres",
      "postgresql",
      "supabase",
      "mysql",
      "sqlite",
      "nosql",
      "mongodb",
      "redis",
    ],
  },
  {
    id: "devops",
    name: "DevOps",
    slug: "devops",
    description: "CI/CD, infra, observability, deployment",
    parentId: null,
    categoryId: "technology",
    type: "concept",
    aliases: ["dev ops", "ci/cd", "ci-cd", "kubernetes", "k8s", "docker", "vercel", "infra"],
  },
  {
    id: "medical-research",
    name: "Medical Research",
    slug: "medical-research",
    description: "Clinical studies, biomedical research",
    parentId: null,
    categoryId: "science",
    type: "topic",
    aliases: ["clinical research", "biomedical research", "clinical trials", "医学研究"],
  },

  // ── Design ────────────────────────────────────────────────────────────
  {
    id: "web-design",
    name: "Web Design",
    slug: "web-design",
    description: "Visual and interaction design for the web",
    parentId: null,
    categoryId: "design",
    type: "concept",
    aliases: ["web ui", "website design", "visual design", "网页设计"],
  },
  {
    id: "product-design",
    name: "Product Design",
    slug: "product-design",
    description: "Software product design and craft",
    parentId: null,
    categoryId: "design",
    type: "concept",
    aliases: ["ux", "user experience", "ui design", "ui/ux", "interaction design"],
  },

  // ── Business ──────────────────────────────────────────────────────────
  {
    id: "branding",
    name: "Branding",
    slug: "branding",
    description: "Brand identity, voice, positioning",
    parentId: null,
    categoryId: "business",
    type: "topic",
    aliases: ["brand", "brand identity", "brand strategy", "brand voice", "品牌"],
  },
  {
    id: "marketing",
    name: "Marketing",
    slug: "marketing",
    description: "Growth, content, distribution, advertising",
    parentId: null,
    categoryId: "business",
    type: "topic",
    aliases: ["growth", "growth marketing", "content marketing", "advertising", "市场营销"],
  },
  {
    id: "startup",
    name: "Startup",
    slug: "startup",
    description: "Founding, fundraising, product-market fit",
    parentId: null,
    categoryId: "business",
    type: "topic",
    aliases: ["startups", "founder", "founders", "vc", "venture capital", "fundraising", "创业"],
  },
  {
    id: "product-strategy",
    name: "Product Strategy",
    slug: "product-strategy",
    description: "Roadmaps, positioning, prioritization",
    parentId: null,
    categoryId: "business",
    type: "concept",
    aliases: ["roadmap", "product roadmap", "go to market", "go-to-market", "gtm"],
  },

  // ── Education ─────────────────────────────────────────────────────────
  {
    id: "learning-systems",
    name: "Learning Systems",
    slug: "learning-systems",
    description: "Spaced repetition, feedback loops, curriculum",
    parentId: null,
    categoryId: "education",
    type: "concept",
    aliases: ["spaced repetition", "anki", "feedback loops", "curriculum design"],
  },
  {
    id: "pedagogy",
    name: "Pedagogy",
    slug: "pedagogy",
    description: "Teaching methods and theory",
    parentId: null,
    categoryId: "education",
    type: "concept",
    aliases: ["teaching", "teaching method", "teaching methods", "educational theory", "教学法"],
  },
  {
    id: "student-development",
    name: "Student Development",
    slug: "student-development",
    description: "Skill growth, mentoring, talent",
    parentId: null,
    categoryId: "education",
    type: "topic",
    aliases: ["mentoring", "talent development", "student growth", "学生发展"],
  },

  // ── Music ─────────────────────────────────────────────────────────────
  {
    id: "piano",
    name: "Piano",
    slug: "piano",
    description: "Piano performance, practice, repertoire",
    parentId: null,
    categoryId: "music",
    type: "topic",
    aliases: ["piano practice", "piano performance", "piano repertoire", "钢琴"],
  },
  {
    id: "music-education",
    name: "Music Education",
    slug: "music-education",
    description: "Music teaching, curriculum, training",
    parentId: null,
    categoryId: "music",
    type: "concept",
    aliases: ["music teaching", "music curriculum", "music school", "音乐教育"],
  },
  {
    id: "festival",
    name: "Festival",
    slug: "festival",
    description: "Festivals, summer programs, masterclasses",
    parentId: null,
    categoryId: "music",
    type: "topic",
    aliases: ["festivals", "summer festival", "summer program", "summer programs", "masterclass"],
  },
  {
    id: "performance",
    name: "Performance",
    slug: "performance",
    description: "Concert performance, stage craft",
    parentId: null,
    categoryId: "music",
    type: "concept",
    aliases: ["performances", "concert", "concerts", "stage performance"],
  },

  // ── Health ────────────────────────────────────────────────────────────
  {
    id: "longevity",
    name: "Longevity",
    slug: "longevity",
    description: "Lifespan, healthspan, anti-aging research",
    parentId: null,
    categoryId: "health",
    type: "topic",
    aliases: ["healthspan", "lifespan", "anti aging", "anti-aging", "antiaging"],
  },
  {
    id: "fitness",
    name: "Fitness",
    slug: "fitness",
    description: "Exercise, training, athletic performance",
    parentId: null,
    categoryId: "health",
    type: "topic",
    aliases: ["exercise", "training", "workout", "workouts", "strength training"],
  },
  {
    id: "nutrition",
    name: "Nutrition",
    slug: "nutrition",
    description: "Diet, supplements, food science",
    parentId: null,
    categoryId: "health",
    type: "topic",
    aliases: ["diet", "diets", "supplement", "supplements", "food science"],
  },

  // ── Science ───────────────────────────────────────────────────────────
  {
    id: "neuroscience",
    name: "Neuroscience",
    slug: "neuroscience",
    description: "Brain, cognition, neural systems",
    parentId: null,
    categoryId: "science",
    type: "topic",
    aliases: ["brain science", "cognitive neuroscience", "neural", "脑科学"],
  },
  {
    id: "biology",
    name: "Biology",
    slug: "biology",
    description: "Life sciences and biological systems",
    parentId: null,
    categoryId: "science",
    type: "topic",
    aliases: ["life sciences", "molecular biology", "生物学"],
  },

  // ── Personal Growth ───────────────────────────────────────────────────
  {
    id: "productivity",
    name: "Productivity",
    slug: "productivity",
    description: "Focus, systems, time management",
    parentId: null,
    categoryId: "personal",
    type: "topic",
    aliases: ["time management", "focus", "deep work", "gtd", "productivity systems"],
  },
  {
    id: "habits",
    name: "Habits",
    slug: "habits",
    description: "Habit design, behavior change, routines",
    parentId: null,
    categoryId: "personal",
    type: "topic",
    aliases: ["habit", "behavior change", "atomic habits", "routine", "routines"],
  },
  {
    id: "philosophy",
    name: "Philosophy",
    slug: "philosophy",
    description: "Mindset, ethics, ways of thinking",
    parentId: null,
    categoryId: "personal",
    type: "topic",
    aliases: ["stoicism", "ethics", "mindset", "哲学"],
  },

  // ── World & Culture ───────────────────────────────────────────────────
  {
    id: "geopolitics",
    name: "Geopolitics",
    slug: "geopolitics",
    description: "International relations, policy, economics",
    parentId: null,
    categoryId: "world",
    type: "topic",
    aliases: ["politics", "international relations", "policy", "economics", "geopolitical"],
  },
  {
    id: "history",
    name: "History",
    slug: "history",
    description: "Historical events, eras, biographies",
    parentId: null,
    categoryId: "world",
    type: "topic",
    aliases: ["historical", "biography", "biographies", "历史"],
  },
];
