import type { GeminiResponseSchema } from "@/lib/ai/gemini-text";

export const VaultAutofillGeminiSchema: GeminiResponseSchema = {
  type: "object",
  required: [
    "app_name",
    "category",
    "platforms",
    "use_cases",
    "summary",
    "best_feature",
    "biggest_downside",
    "best_alternative",
    "replaces",
    "default_tool_for",
    "tags",
    "why_i_use_it",
    "cost_type",
    "pricing_plans",
    "alternative_options",
    "field_confidence",
  ],
  properties: {
    app_name: { type: "string" },
    website_url: { type: "string" },
    github_url: { type: "string" },
    category: { type: "string" },
    platforms: { type: "string" },
    use_cases: { type: "string" },
    status: { type: "string" },
    priority: { type: "string" },
    cost_type: { type: "string" },
    cost_amount: { type: "number" },
    cost_period: { type: "string" },
    cost_currency: { type: "string" },
    summary: { type: "string" },
    best_feature: { type: "string" },
    biggest_downside: { type: "string" },
    best_alternative: { type: "string" },
    replaces: { type: "string" },
    default_tool_for: { type: "string" },
    tags: {
      type: "array",
      items: { type: "string" },
    },
    why_i_use_it: { type: "string" },
    pricing_plans: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          price: { type: "number" },
          currency: { type: "string" },
          billing_cycle: { type: "string" },
          cost_type: { type: "string" },
          features: { type: "array", items: { type: "string" } },
          source_url: { type: "string" },
          confidence: { type: "string" },
        },
      },
    },
    alternative_options: {
      type: "array",
      items: {
        type: "object",
        properties: {
          name: { type: "string" },
          reason: { type: "string" },
          confidence: { type: "string" },
        },
      },
    },
    field_confidence: {
      type: "object",
      properties: {
        app_name: { type: "string" },
        category: { type: "string" },
        summary: { type: "string" },
        best_alternative: { type: "string" },
      },
    },
  },
};
