import type { VaultCuratedStackTemplate } from "@/lib/vault/software-library-schema";
import { libTool } from "@/lib/vault/stack-seeds/lib-tool";

/** Marketing / Growth, Sales / BD, Customer Support / CX (9 archetypes). */
export const VAULT_STACK_SEEDS_BATCH_03: VaultCuratedStackTemplate[] = [
  {
    id: "marketing_growth-content-engine",
    name: "Content Engine Stack",
    industry: "marketing_growth",
    role: "Content marketing lead",
    summary: "HubSpot Breeze for CRM-tied campaigns, Canva for creative, Adobe Firefly for brand imagery, ChatGPT for copy variants.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Always-on content pipeline with measurable pipeline impact.",
    team_size_fit: "Growth teams 5–40",
    recommended_for: "HubSpot Marketing Hub customers.",
    not_ideal_for: "Teams without brand governance for generative assets.",
    tools: [
      libTool("hubspot-breeze-ce", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "AI blog/email ideas tied to segments",
        workflow_tags: ["crm", "marketing"],
      }),
      libTool("canva-ce", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Social kits, carousels, and motion snippets",
        workflow_tags: ["design"],
      }),
      libTool("adobe-firefly-ce", "Adobe Firefly", {
        website_url: "https://www.adobe.com/products/firefly.html",
        category: "Generative design",
        role_in_stack: "Brand-safe hero imagery",
        workflow_tags: ["ai_media", "design"],
      }),
      libTool("chatgpt-business-ce", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Headlines, nurture angles, and landing tests",
        workflow_tags: ["writing"],
      }),
    ],
    rationale: "Content engines need CRM context plus creative velocity; HubSpot plus Canva/Firefly keeps output on-brand.",
    tradeoffs: ["Creative overlap if Firefly and Canva both produce hero art."],
    setup_order: ["Sync brand kit to Firefly", "Template HubSpot campaigns", "Define ChatGPT tone guide"],
  },
  {
    id: "marketing_growth-crm-native-growth",
    name: "CRM-native Growth Stack",
    industry: "marketing_growth",
    role: "RevOps + demand gen",
    summary: "HubSpot Breeze plus Salesforce Agentforce, Canva for creative, Zapier for glue.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "elevated",
    workflow_fit: "Dual-CRM or migrating teams needing AI on both stacks.",
    team_size_fit: "Mid-market with Salesforce and HubSpot overlap",
    recommended_for: "Organizations harmonizing Salesforce and HubSpot motions.",
    not_ideal_for: "Tiny teams without admin capacity for two CRMs.",
    tools: [
      libTool("hubspot-breeze-crm", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Inbound nurture and handoffs",
        workflow_tags: ["crm", "marketing"],
      }),
      libTool("salesforce-agentforce-mkt", "Salesforce Agentforce", {
        website_url: "https://www.salesforce.com/agentforce",
        category: "CRM + AI",
        role_in_stack: "Agentic workflows on Salesforce data",
        workflow_tags: ["crm", "sales"],
      }),
      libTool("canva-crm", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Partner and ABM creative kits",
        workflow_tags: ["design"],
      }),
      libTool("zapier-crm", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Bi-directional sync and alerts",
        workflow_tags: ["automation"],
      }),
    ],
    rationale: "CRM-native growth needs AI on both systems of record with automation to prevent drift.",
    tradeoffs: ["Integration complexity and license overlap."],
    setup_order: ["Map systems of record per object", "Pilot Agentforce on one journey", "Automate lead sync with Zapier"],
  },
  {
    id: "marketing_growth-research-performance",
    name: "Research & Performance Stack",
    industry: "marketing_growth",
    role: "Performance marketer",
    summary: "Perplexity for grounded research, Gemini in Workspace for analysis decks, HubSpot Breeze for activation, Airtable for experiments.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Research → hypothesis → experiment log → CRM activation.",
    team_size_fit: "Pods of 3–15",
    recommended_for: "Google Workspace teams running disciplined growth tests.",
    not_ideal_for: "Microsoft-only orgs without Workspace.",
    tools: [
      libTool("perplexity-rp", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Market and competitor briefs with citations",
        workflow_tags: ["research"],
      }),
      libTool("google-workspace-gemini-rp", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Sheets analysis and Slides storytelling",
        workflow_tags: ["google_workspace"],
      }),
      libTool("hubspot-breeze-rp", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Campaign builds from research notes",
        workflow_tags: ["crm", "marketing"],
      }),
      libTool("airtable-rp", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Experimentation",
        role_in_stack: "Test backlog, creatives, and readouts",
        workflow_tags: ["database", "analytics"],
      }),
    ],
    rationale: "Performance marketing needs defensible research plus a lightweight experiment ledger before CRM spend.",
    tradeoffs: ["Manual discipline required to log tests in Airtable."],
    setup_order: ["Create experiment schema in Airtable", "Train team on Perplexity sourcing", "Connect HubSpot lists to tests"],
  },
  {
    id: "sales_bd-prospecting",
    name: "Prospecting Stack",
    industry: "sales_bd",
    role: "SDR / AE hybrid",
    summary: "Salesforce Agentforce Sales, HubSpot Breeze, Perplexity for account intel, Fireflies for discovery calls.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "elevated",
    workflow_fit: "Outbound plus multi-threaded enterprise deals.",
    team_size_fit: "10–200 sellers",
    recommended_for: "Salesforce-first orgs augmenting with HubSpot for inbound.",
    not_ideal_for: "SMB-only teams without Salesforce admin.",
    tools: [
      libTool("salesforce-agentforce-sales", "Salesforce Agentforce Sales", {
        website_url: "https://www.salesforce.com/agentforce",
        category: "CRM + AI",
        role_in_stack: "Agentic prospecting and opportunity updates",
        workflow_tags: ["crm", "sales"],
      }),
      libTool("hubspot-breeze-prospect", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Inbound qualification and nurture",
        workflow_tags: ["crm", "marketing"],
      }),
      libTool("perplexity-prospect", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Account plans with cited news",
        workflow_tags: ["research"],
      }),
      libTool("fireflies-prospect", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Discovery call insights to CRM",
        workflow_tags: ["meetings"],
      }),
    ],
    rationale: "Prospecting stacks win when AI updates CRM objects while research stays cited and calls become structured data.",
    tradeoffs: ["Dual CRM maintenance if not harmonized."],
    setup_order: ["Define lead routing between HubSpot and Salesforce", "Train Perplexity sourcing SOPs", "Map Fireflies → CRM fields"],
  },
  {
    id: "sales_bd-smb-sales",
    name: "SMB Sales Stack",
    industry: "sales_bd",
    role: "SMB AE",
    summary: "HubSpot Breeze for sequences, ChatGPT for outreach, Zoom AI Companion for demos, Zapier for lead routing.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "High-velocity SMB cycles with light tooling.",
    team_size_fit: "1–40 sellers",
    recommended_for: "HubSpot-native SMB revenue teams.",
    not_ideal_for: "Complex CPQ on Salesforce-only stacks.",
    tools: [
      libTool("hubspot-breeze-smb", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Sequences, tasks, and deal coaching",
        workflow_tags: ["crm", "sales"],
      }),
      libTool("chatgpt-business-smb-sales", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Personalization at scale for outreach",
        workflow_tags: ["writing"],
      }),
      libTool("zoom-ai-smb-sales", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Demo summaries and follow-ups",
        workflow_tags: ["video"],
      }),
      libTool("zapier-smb-sales", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Lead forms → CRM tasks",
        workflow_tags: ["automation"],
      }),
    ],
    rationale: "SMB sales needs fast personalization without brittle spreadsheets; HubSpot plus ChatGPT keeps reps in flow.",
    tradeoffs: ["Quality depends on prompt hygiene and CRM hygiene."],
    setup_order: ["Clean HubSpot properties", "Publish outreach prompt library", "Wire Zapier for inbound SLAs"],
  },
  {
    id: "sales_bd-enterprise-account-planning",
    name: "Enterprise Account Planning Stack",
    industry: "sales_bd",
    role: "Strategic AE",
    summary: "Salesforce Agentforce, Slack for deal rooms, Perplexity for research, Microsoft 365 Copilot for exec-ready decks.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "Multi-threaded enterprise pursuits with Microsoft stack.",
    team_size_fit: "Global account teams",
    recommended_for: "Microsoft + Salesforce enterprises.",
    not_ideal_for: "Google-only collaboration environments.",
    tools: [
      libTool("salesforce-agentforce-ent", "Salesforce Agentforce", {
        website_url: "https://www.salesforce.com/agentforce",
        category: "CRM + AI",
        role_in_stack: "Account intelligence and next-best actions",
        workflow_tags: ["crm", "sales"],
      }),
      libTool("slackbot-ent-sales", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Deal rooms and exec brief threads",
        workflow_tags: ["chat"],
      }),
      libTool("perplexity-ent-sales", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Cited industry and regulatory context",
        workflow_tags: ["research"],
      }),
      libTool("ms365-copilot-ent-sales", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "PowerPoint/Word for QBR narratives",
        workflow_tags: ["copilot"],
      }),
    ],
    rationale: "Enterprise pursuits need authoritative CRM signals, tight collaboration, and research-grade citations.",
    tradeoffs: ["Requires strong data hygiene in Salesforce to avoid hallucinated context."],
    setup_order: ["Normalize account teams in Slack", "Enable Copilot with approved templates", "Train Perplexity sourcing"],
  },
  {
    id: "customer_support_cx-ai-first-support",
    name: "AI-first Support Stack",
    industry: "customer_support_cx",
    role: "CX manager",
    summary: "Intercom Fin for AI support, Slack for escalations, Fireflies for voice-of-customer, Airtable for issue analytics.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Digital-first support with human escalation paths.",
    team_size_fit: "10–200 agents",
    recommended_for: "Product-led SaaS with Intercom.",
    not_ideal_for: "Phone-only contact centers without Intercom.",
    tools: [
      libTool("intercom-fin", "Intercom Fin", {
        website_url: "https://www.intercom.com",
        category: "Support AI",
        role_in_stack: "AI answers grounded in help center",
        workflow_tags: ["support", "ai_assistant"],
      }),
      libTool("slackbot-cx", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Escalations to product and engineering",
        workflow_tags: ["chat"],
      }),
      libTool("fireflies-cx", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Sales-to-support handoff context",
        workflow_tags: ["meetings"],
      }),
      libTool("airtable-cx", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Analytics",
        role_in_stack: "Issue themes and backlog prioritization",
        workflow_tags: ["database", "support"],
      }),
    ],
    rationale: "AI-first support needs grounded bots plus structured analytics so humans focus on novel failures.",
    tradeoffs: ["Help center quality directly caps Fin effectiveness."],
    setup_order: ["Harden help center articles", "Wire Slack escalation macros", "Instrument Airtable issue taxonomy"],
  },
  {
    id: "customer_support_cx-salesforce-service",
    name: "Salesforce Service Stack",
    industry: "customer_support_cx",
    role: "Service operations",
    summary: "Salesforce Agentforce for service workflows, Slack for swarming, Zoom AI for video support, Airtable for workforce planning.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "Enterprise service clouds with compliance needs.",
    team_size_fit: "50–5000 agents",
    recommended_for: "Salesforce Service Cloud customers.",
    not_ideal_for: "SMBs without Salesforce footprint.",
    tools: [
      libTool("salesforce-agentforce-svc", "Salesforce Agentforce", {
        website_url: "https://www.salesforce.com/agentforce",
        category: "CRM + AI",
        role_in_stack: "Agentic service flows on CRM data",
        workflow_tags: ["crm", "support"],
      }),
      libTool("slackbot-svc", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Swarming and major incident rooms",
        workflow_tags: ["chat"],
      }),
      libTool("zoom-ai-svc", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "VIP support session summaries",
        workflow_tags: ["video"],
      }),
      libTool("airtable-svc", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Workforce ops",
        role_in_stack: "Scheduling, training, and QA sampling",
        workflow_tags: ["database"],
      }),
    ],
    rationale: "Salesforce-centric service orgs benefit when Agentforce automates routine while Slack handles complex swarms.",
    tradeoffs: ["Requires mature Salesforce data model to avoid brittle automations."],
    setup_order: ["Baseline Service Cloud objects", "Define Slack swarm playbooks", "Pilot Agentforce on tier-1 intents"],
  },
  {
    id: "customer_support_cx-smb-support",
    name: "SMB Support Stack",
    industry: "customer_support_cx",
    role: "Founder-led support",
    summary: "HubSpot Customer Agent / Breeze, Fireflies for sales calls, ChatGPT for macros, Zapier for tickets.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "low",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Lean teams covering sales and support in one inbox.",
    team_size_fit: "1–25",
    recommended_for: "HubSpot Service + CRM Starter customers.",
    not_ideal_for: "Telephony-heavy centers needing CCaaS depth.",
    tools: [
      libTool("hubspot-customer-agent", "HubSpot Customer Agent / Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "AI replies across chat and email",
        workflow_tags: ["support", "crm"],
      }),
      libTool("fireflies-smb-cx", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Capture promises made on sales calls",
        workflow_tags: ["meetings"],
      }),
      libTool("chatgpt-business-smb-cx", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Macro writing and tone adjustment",
        workflow_tags: ["writing"],
      }),
      libTool("zapier-smb-cx", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Form/ticket routing and Slack alerts",
        workflow_tags: ["automation"],
      }),
    ],
    rationale: "SMB support is conversational; HubSpot agents plus ChatGPT keep responses fast without hiring a full QA team.",
    tradeoffs: ["Still need human review for edge cases and refunds."],
    setup_order: ["Seed HubSpot knowledge base", "Template ChatGPT tone for brand", "Automate Zapier triage"],
  },
];
