import type { VaultCuratedStackTemplate } from "@/lib/vault/software-library-schema";
import { libTool } from "@/lib/vault/stack-seeds/lib-tool";

/** Creator / Content, Startup / SME, Operations / BizOps (9 archetypes). */
export const VAULT_STACK_SEEDS_BATCH_02: VaultCuratedStackTemplate[] = [
  {
    id: "creator_content-short-form-video",
    name: "Short-form Video Stack",
    industry: "creator_content",
    role: "Short-form creator",
    summary: "Runway for generative shots, Descript for edits, Canva Magic Studio for packaging, ChatGPT Business for scripts.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Rapid ideation to publish for vertical video.",
    team_size_fit: "Solo to small studio",
    recommended_for: "Creators shipping weekly short-form.",
    not_ideal_for: "Long-form cinematic pipelines needing offline suites.",
    tools: [
      libTool("runway-sf", "Runway", {
        website_url: "https://runwayml.com",
        category: "Generative video",
        role_in_stack: "B-roll, effects, and generative clips",
        workflow_tags: ["video", "ai_media"],
      }),
      libTool("descript-sf", "Descript", {
        website_url: "https://www.descript.com",
        category: "Editing",
        role_in_stack: "Text-based edits and captions",
        workflow_tags: ["video_edit"],
      }),
      libTool("canva-magic-sf", "Canva Magic Studio", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Thumbnails, end cards, and batch variants",
        workflow_tags: ["design"],
      }),
      libTool("chatgpt-business-sf", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Hooks, scripts, and A/B caption tests",
        workflow_tags: ["ai_assistant", "writing"],
      }),
    ],
    rationale: "Short-form rewards tight loops; generative video plus text-based editing keeps iteration cost low.",
    tradeoffs: ["Generative assets need brand review for likeness and music rights."],
    setup_order: ["Lock thumbnail templates in Canva", "Create Descript project presets", "Define Runway style guides"],
  },
  {
    id: "creator_content-brand-content",
    name: "Brand Content Stack",
    industry: "creator_content",
    role: "Brand studio",
    summary: "Adobe Firefly for brand-safe visuals, Canva for social kits, ChatGPT for copy, HubSpot Breeze for CRM-tied campaigns.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Campaigns anchored to brand system and CRM segments.",
    team_size_fit: "Marketing pods of 3–25",
    recommended_for: "HubSpot-first teams needing creative velocity.",
    not_ideal_for: "Brands without Adobe admin to govern Firefly libraries.",
    tools: [
      libTool("adobe-firefly-brand", "Adobe Firefly", {
        website_url: "https://www.adobe.com/products/firefly.html",
        category: "Generative design",
        role_in_stack: "On-brand imagery with enterprise controls",
        workflow_tags: ["design", "ai_media"],
      }),
      libTool("canva-magic-brand", "Canva Magic Studio", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Social grids, animations, and approvals",
        workflow_tags: ["design"],
      }),
      libTool("chatgpt-business-brand", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Campaign narratives and landing copy",
        workflow_tags: ["writing"],
      }),
      libTool("hubspot-breeze-brand", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "AI-assisted emails and journey orchestration",
        workflow_tags: ["crm", "marketing"],
      }),
    ],
    rationale: "Brand teams need CRM context plus safe generative assets; Firefly and HubSpot keep outputs aligned to customers.",
    tradeoffs: ["Tooling overlap if both Canva and Firefly produce similar hero assets."],
    setup_order: ["Sync brand kit into Firefly", "Map HubSpot segments to Canva templates", "Publish copy guidelines for ChatGPT"],
  },
  {
    id: "creator_content-podcast-talking-head",
    name: "Podcast / Talking-head Stack",
    industry: "creator_content",
    role: "Podcaster / YouTube host",
    summary: "Descript for edits, Fireflies for guest calls, ChatGPT for show notes, Canva for episode art, Runway for inserts.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Interview → cut → publish with consistent packaging.",
    team_size_fit: "Solo hosts and micro teams",
    recommended_for: "Weekly interview shows.",
    not_ideal_for: "Multi-track music production needing DAW depth.",
    tools: [
      libTool("descript-pod", "Descript", {
        website_url: "https://www.descript.com",
        category: "Editing",
        role_in_stack: "Remove filler, overdub, and audiogram exports",
        workflow_tags: ["video_edit", "audio"],
      }),
      libTool("fireflies-pod", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Transcripts and pull-quotes from recordings",
        workflow_tags: ["meetings", "transcription"],
      }),
      libTool("chatgpt-business-pod", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Titles, chapters, and newsletter drafts",
        workflow_tags: ["writing"],
      }),
      libTool("canva-pod", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Episode covers and audiogram visuals",
        workflow_tags: ["design"],
      }),
      libTool("runway-pod", "Runway", {
        website_url: "https://runwayml.com",
        category: "Generative video",
        role_in_stack: "Short inserts and stylized bumpers",
        workflow_tags: ["video"],
      }),
    ],
    rationale: "Podcast workflows are transcript-first; Descript plus Fireflies collapses edit prep while Runway spices visuals.",
    tradeoffs: ["Multiple AI summaries if both Descript and Fireflies run on same file."],
    setup_order: ["Normalize Descript project template", "Connect Fireflies to calendar", "Batch Canva episode kit"],
  },
  {
    id: "startup_sme-lean-founder",
    name: "Lean Founder Stack",
    industry: "startup_sme",
    role: "Founder / GM",
    summary: "ChatGPT for strategy copy, HubSpot Breeze for CRM, Zapier glue, Slack for decisions, Canva for outbound visuals.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "low",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "GTM experiments with minimal headcount.",
    team_size_fit: "1–30",
    recommended_for: "Early revenue teams on HubSpot Starter+.",
    not_ideal_for: "Complex product delivery needing Jira depth day one.",
    tools: [
      libTool("chatgpt-business-founder", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "ICP narratives, outbound drafts, and investor updates",
        workflow_tags: ["writing", "ai_assistant"],
      }),
      libTool("hubspot-breeze-founder", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Sequences, deal notes, and lightweight forecasting",
        workflow_tags: ["crm", "sales"],
      }),
      libTool("zapier-founder", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Lead capture, billing alerts, and Slack routing",
        workflow_tags: ["automation"],
      }),
      libTool("slackbot-founder", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Daily standups and customer escalation rooms",
        workflow_tags: ["chat"],
      }),
      libTool("canva-founder", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "One-pagers, social, and pitch visuals",
        workflow_tags: ["design"],
      }),
    ],
    rationale: "Founders need one spine for customers (HubSpot) plus fast comms (Slack) and pragmatic automation (Zapier).",
    tradeoffs: ["HubSpot depth may lag Salesforce for complex enterprise cycles."],
    setup_order: ["Define HubSpot pipeline stages", "Wire Zapier for lead forms", "Create Canva pitch kit"],
  },
  {
    id: "startup_sme-microsoft-native",
    name: "Microsoft-native SME Stack",
    industry: "startup_sme",
    role: "COO / Ops lead",
    summary: "Microsoft 365 Copilot across Office, Airtable for ops data, Zoom AI Companion, Zapier bridges, Fireflies for sales calls.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Teams standardized on Microsoft 365 and Zoom.",
    team_size_fit: "20–250",
    recommended_for: "SMBs with Entra ID and Teams culture.",
    not_ideal_for: "Google Workspace-native orgs without migration plan.",
    tools: [
      libTool("ms365-copilot-sme", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "Excel/Outlook/Teams copilots",
        workflow_tags: ["copilot", "microsoft_365"],
      }),
      libTool("airtable-sme", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Operations DB",
        role_in_stack: "Inventory, hiring pipeline, and vendor lists",
        workflow_tags: ["database"],
      }),
      libTool("zoom-ai-sme", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Customer call summaries",
        workflow_tags: ["video", "meetings"],
      }),
      libTool("zapier-sme", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "CRM, billing, and HRIS handoffs",
        workflow_tags: ["automation"],
      }),
      libTool("fireflies-sme", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Capture sales discovery details",
        workflow_tags: ["meetings"],
      }),
    ],
    rationale: "Microsoft-native SMBs benefit when Copilot augments existing files while Airtable adds flexible ops views.",
    tradeoffs: ["Potential overlap between Zoom AI summaries and Copilot meeting notes."],
    setup_order: ["Enable Copilot licenses by persona", "Model Airtable bases per function", "Policy Fireflies recording consent"],
  },
  {
    id: "startup_sme-google-native",
    name: "Google-native SME Stack",
    industry: "startup_sme",
    role: "Head of remote ops",
    summary: "Gemini in Workspace, Slack for async, Airtable for planning, Zapier automations, Canva for GTM assets.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Distributed teams living in Gmail/Meet/Drive.",
    team_size_fit: "5–120",
    recommended_for: "Startups on Google Workspace needing light ERP substitutes.",
    not_ideal_for: "Heavily regulated orgs needing Microsoft-only stacks.",
    tools: [
      libTool("google-workspace-gemini-sme", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Gemini in Gmail, Docs, Sheets, Meet",
        workflow_tags: ["google_workspace"],
      }),
      libTool("slackbot-sme-g", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Cross-tool notifications and incident rooms",
        workflow_tags: ["chat"],
      }),
      libTool("airtable-sme-g", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Operations DB",
        role_in_stack: "Roadmaps, hiring, and vendor tracking",
        workflow_tags: ["database"],
      }),
      libTool("zapier-sme-g", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Forms → Sheets → Slack",
        workflow_tags: ["automation"],
      }),
      libTool("canva-sme-g", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Launch assets and investor one-pagers",
        workflow_tags: ["design"],
      }),
    ],
    rationale: "Google-native SMBs move fast when Gemini augments mail/docs while Slack and Airtable coordinate execution.",
    tradeoffs: ["Slack plus Google Chat duplication if both are active."],
    setup_order: ["Configure Gemini OU policies", "Standardize Airtable views per squad", "Publish Zapier playbook"],
  },
  {
    id: "operations_bizops-process-automation",
    name: "Process Automation Stack",
    industry: "operations_bizops",
    role: "BizOps manager",
    summary: "Airtable as flexible system of record, Zapier for no-code flows, Make AI Agents for branching logic, Slack for human steps.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Cross-system orchestration without heavy engineering.",
    team_size_fit: "Ops teams 3–40",
    recommended_for: "Teams needing quick automation without standing up k8s.",
    not_ideal_for: "Ultra-low-latency transactional systems.",
    tools: [
      libTool("airtable-bizops", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Operations DB",
        role_in_stack: "Requests, assets, and workflow states",
        workflow_tags: ["database"],
      }),
      libTool("zapier-bizops", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Simple multi-step connectors",
        workflow_tags: ["automation"],
      }),
      libTool("make-ai-agents", "Make AI Agents", {
        website_url: "https://www.make.com",
        category: "Automation",
        role_in_stack: "Branching scenarios with AI steps",
        workflow_tags: ["automation", "ai_assistant"],
      }),
      libTool("slackbot-bizops", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Human approvals and exception handling",
        workflow_tags: ["chat"],
      }),
    ],
    rationale: "BizOps wins when flexible tables meet pragmatic automation and humans stay in the loop in Slack.",
    tradeoffs: ["Make vs Zapier overlap if both trigger on same events—document owners."],
    setup_order: ["Model Airtable request lifecycle", "Prototype flows in Zapier", "Add Make agents for exceptions"],
  },
  {
    id: "operations_bizops-privacy-sensitive",
    name: "Privacy-sensitive Ops Stack",
    industry: "operations_bizops",
    role: "Security-conscious ops",
    summary: "Airtable for structured ops data, self-hosted n8n for automation, Slack for coordination, Perplexity Enterprise for research.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "Internal workflows with preference for self-hosted automation.",
    team_size_fit: "10–200",
    recommended_for: "Teams that can operate n8n with infra support.",
    not_ideal_for: "Teams without DevOps to patch automation workers.",
    tools: [
      libTool("airtable-priv", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Operations DB",
        role_in_stack: "Structured requests with field-level permissions",
        workflow_tags: ["database"],
      }),
      libTool("n8n", "n8n", {
        website_url: "https://n8n.io",
        category: "Automation",
        role_in_stack: "Self-hosted workflows and AI nodes",
        workflow_tags: ["automation", "self_hosted"],
      }),
      libTool("slackbot-priv", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Human-in-the-loop approvals",
        workflow_tags: ["chat"],
      }),
      libTool("perplexity-enterprise-priv", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Cited vendor and policy lookups",
        workflow_tags: ["research"],
      }),
    ],
    rationale: "Privacy-sensitive ops still needs automation; n8n plus enterprise Perplexity keeps workloads controllable.",
    tradeoffs: ["Self-hosted n8n adds patching and secrets management burden."],
    setup_order: ["Deploy n8n with SSO", "Lock Airtable bases to least privilege", "Document Slack approval paths"],
  },
  {
    id: "operations_bizops-meeting-to-execution",
    name: "Meeting-to-Execution Stack",
    industry: "operations_bizops",
    role: "Chief of staff",
    summary: "Fireflies for meeting memory, Airtable for action trackers, Zapier for handoffs, Slack for owners, Zoom AI for live support.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Leadership meetings → tracked actions with owners.",
    team_size_fit: "Leadership teams 5–50",
    recommended_for: "Exec teams drowning in recurring meetings.",
    not_ideal_for: "Cultures avoiding recorded conversations.",
    tools: [
      libTool("fireflies-exec", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Searchable archive of decisions",
        workflow_tags: ["meetings", "transcription"],
      }),
      libTool("airtable-exec", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Tracking",
        role_in_stack: "Action items with owners and due dates",
        workflow_tags: ["database"],
      }),
      libTool("zapier-exec", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Push highlights into Slack and CRM",
        workflow_tags: ["automation"],
      }),
      libTool("slackbot-exec", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Nudge owners and surface blockers",
        workflow_tags: ["chat"],
      }),
      libTool("zoom-ai-exec", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Live summaries during leadership forums",
        workflow_tags: ["video"],
      }),
    ],
    rationale: "Execution breaks when meetings lack memory; Fireflies plus Airtable converts talk into owned work.",
    tradeoffs: ["Overlapping summaries if Zoom AI and Fireflies both run—pick a primary."],
    setup_order: ["Define recording policy", "Template Airtable action tracker", "Wire Zapier to Slack reminders"],
  },
];
