import type { VaultCuratedStackTemplate } from "@/lib/vault/software-library-schema";
import { libTool } from "@/lib/vault/stack-seeds/lib-tool";

/** Finance & Accounting, Legal, Education (9 archetypes). */
export const VAULT_STACK_SEEDS_BATCH_01: VaultCuratedStackTemplate[] = [
  {
    id: "finance_accounting-fpa-reporting",
    name: "FP&A / Reporting Stack",
    industry: "finance_accounting",
    role: "FP&A / Controllership",
    summary:
      "Office-native copilots, grounded research, QuickBooks financials, Airtable planning models, and Zapier glue for recurring close workflows.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Close, forecast packs, board-ready variance narratives.",
    team_size_fit: "10–500 person finance orgs on Microsoft 365.",
    recommended_for: "Teams needing faster research-to-slide cycles without abandoning Excel culture.",
    not_ideal_for: "Regimes that prohibit third-party LLM research without enterprise contracts.",
    tools: [
      libTool("ms365-copilot", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "Drafting, summarization, and meeting follow-ups inside M365",
        workflow_tags: ["copilot", "microsoft_365"],
      }),
      libTool("perplexity-enterprise-pro", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Cited market and policy research for memos",
        workflow_tags: ["research", "ai_assistant"],
      }),
      libTool("intuit-quickbooks", "Intuit Assist / QuickBooks ecosystem", {
        website_url: "https://quickbooks.intuit.com",
        category: "Accounting",
        role_in_stack: "Books, payroll, and AI-assisted categorization",
        workflow_tags: ["accounting", "finance_ops"],
      }),
      libTool("airtable", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Data workspace",
        role_in_stack: "Headcount, OPEX models, and scenario tables",
        workflow_tags: ["planning", "database"],
      }),
      libTool("zapier", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Connectors between finance systems and notifications",
        workflow_tags: ["automation", "integrations"],
      }),
    ],
    rationale:
      "FP&A teams live in spreadsheets and email; this stack keeps AI inside approved surfaces while still accelerating research and operational reporting.",
    tradeoffs: ["Vendor overlap between Copilot and Perplexity if governance is unclear."],
    setup_order: [
      "Confirm AI data-handling policies for Copilot and Perplexity",
      "Standardize Airtable bases for forecast drivers",
      "Map Zapier flows for close-week alerts",
    ],
  },
  {
    id: "finance_accounting-smb-finance-ops",
    name: "Small Business Finance Ops Stack",
    industry: "finance_accounting",
    role: "Owner / Finance generalist",
    summary:
      "Chat-led analysis, QuickBooks as system of record, Slack for approvals, Zapier automations, and Fireflies for invoice context from calls.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Invoices, light forecasting, and cash visibility for SMBs.",
    team_size_fit: "1–50 employees",
    recommended_for: "Founders who want pragmatic automation without a heavy ERP.",
    not_ideal_for: "Multi-entity consolidations or strict segregation-of-duties programs.",
    tools: [
      libTool("chatgpt-business", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Variance explanations and vendor outreach drafts",
        workflow_tags: ["ai_assistant", "writing"],
      }),
      libTool("intuit-quickbooks-smb", "Intuit Assist / QuickBooks", {
        website_url: "https://quickbooks.intuit.com",
        category: "Accounting",
        role_in_stack: "Core ledger, bills, and tax prep handoffs",
        workflow_tags: ["accounting"],
      }),
      libTool("slackbot", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Approvals, reminders, and finance channel hygiene",
        workflow_tags: ["chat", "notifications"],
      }),
      libTool("zapier-smb", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Bank feeds, CRM invoices, and lightweight workflows",
        workflow_tags: ["automation"],
      }),
      libTool("fireflies", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Capture vendor and lender call details into tasks",
        workflow_tags: ["meetings", "transcription"],
      }),
    ],
    rationale:
      "SMB finance is conversational; pairing ChatGPT with QuickBooks plus Slack keeps decisions fast while preserving an audit-friendly trail.",
    tradeoffs: ["Meeting-note tools need clear retention policies for sensitive numbers."],
    setup_order: [
      "Normalize QuickBooks chart of accounts",
      "Create Slack approval channels with Zapier triggers",
      "Pilot Fireflies on external finance calls only",
    ],
  },
  {
    id: "finance_accounting-research-heavy",
    name: "Research-heavy Finance Stack",
    industry: "finance_accounting",
    role: "Research / IR / Corp dev",
    summary:
      "Business-grade models, Perplexity for cited research, Gemini in Workspace, Airtable for thesis tracking, and Zoom AI Companion for live briefings.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Deep dives, comps, and narrative updates ahead of investor weeks.",
    team_size_fit: "Distributed research pods",
    recommended_for: "Teams already standardized on Google Workspace plus Zoom.",
    not_ideal_for: "Air-gapped research environments.",
    tools: [
      libTool("chatgpt-business-r", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Model commentary and scenario drafting",
        workflow_tags: ["ai_assistant"],
      }),
      libTool("perplexity-enterprise-pro-r", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Cited pulls for filings, macro, and sector notes",
        workflow_tags: ["research"],
      }),
      libTool("google-workspace-gemini", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Docs/Sheets/Slides copilots with enterprise controls",
        workflow_tags: ["google_workspace", "documents"],
      }),
      libTool("airtable-r", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Research ops",
        role_in_stack: "Comparable company grids and diligence trackers",
        workflow_tags: ["database", "research"],
      }),
      libTool("zoom-ai-companion", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Live summaries and follow-ups for expert calls",
        workflow_tags: ["video", "meetings"],
      }),
    ],
    rationale:
      "Research-heavy finance needs defensible citations plus collaborative surfaces; this stack pairs grounded search with Workspace-native drafting.",
    tradeoffs: ["Multiple AI assistants can duplicate spend if not role-split clearly."],
    setup_order: [
      "Enable Gemini enterprise controls in Workspace admin",
      "Create Airtable diligence templates",
      "Train analysts on Perplexity citation norms",
    ],
  },
  {
    id: "legal-solo-small-firm",
    name: "Solo / Small Firm Stack",
    industry: "legal",
    role: "Managing attorney",
    summary:
      "Clio for matters, ChatGPT for drafting support, Perplexity for research, Fireflies for client calls, and Microsoft 365 Copilot inside Word/Outlook.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "strict_compliance",
    workflow_fit: "Matter intake through signing with tight documentation.",
    team_size_fit: "1–15 attorneys",
    recommended_for: "Firms already on Microsoft 365 needing modern matter ops.",
    not_ideal_for: "Clients forbidding any generative drafting assistance.",
    tools: [
      libTool("clio-manage-ai", "Clio Manage AI", {
        website_url: "https://www.clio.com",
        category: "Practice management",
        role_in_stack: "Matters, billing, and AI-assisted intake",
        workflow_tags: ["legal_ops", "crm"],
      }),
      libTool("chatgpt-business-legal", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "First-pass memos and client correspondence drafts",
        workflow_tags: ["ai_assistant", "writing"],
      }),
      libTool("perplexity-enterprise-legal", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Cited legal research with exportable notes",
        workflow_tags: ["research"],
      }),
      libTool("fireflies-legal", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Capture consult details and next steps",
        workflow_tags: ["meetings"],
      }),
      libTool("ms365-copilot-legal", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "Word/Outlook drafting with firm templates",
        workflow_tags: ["copilot", "documents"],
      }),
    ],
    rationale:
      "Small firms win when matter data stays authoritative in Clio while AI accelerates drafting and research with clear guardrails.",
    tradeoffs: ["You must configure retention and confidentiality per tool."],
    setup_order: [
      "Harden Clio matter stages and conflict checks",
      "Deploy M365 Copilot with firm style guides",
      "Pilot Fireflies only on approved call types",
    ],
  },
  {
    id: "legal-in-house-counsel",
    name: "In-house Counsel Stack",
    industry: "legal",
    role: "GC office",
    summary:
      "Harvey for legal workflows, Copilot in Microsoft stack, Perplexity for research, Slack for cross-functional intake, Zoom AI for exec briefings.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "High-stakes drafting with enterprise security expectations.",
    team_size_fit: "Central legal teams supporting product and GTM",
    recommended_for: "Microsoft-centric enterprises evaluating legal LLMs.",
    not_ideal_for: "Organizations without vendor risk reviews for Harvey.",
    tools: [
      libTool("harvey", "Harvey", {
        website_url: "https://www.harvey.ai",
        category: "Legal AI",
        role_in_stack: "Contract review and knowledge workflows",
        workflow_tags: ["legal_ai", "documents"],
      }),
      libTool("ms365-copilot-ih", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "Policy drafting inside Word/PowerPoint",
        workflow_tags: ["copilot"],
      }),
      libTool("perplexity-enterprise-ih", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Regulatory monitoring with citations",
        workflow_tags: ["research"],
      }),
      libTool("slackbot-ih", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Legal intake from product and sales channels",
        workflow_tags: ["chat"],
      }),
      libTool("zoom-ai-companion-ih", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Summaries for cross-functional legal reviews",
        workflow_tags: ["video"],
      }),
    ],
    rationale:
      "In-house teams need enterprise-grade models tied to Microsoft identity while keeping research auditable and intake orderly in Slack.",
    tradeoffs: ["Overlapping summarization between Zoom AI and Copilot if not governed."],
    setup_order: [
      "Complete Harvey security review and data maps",
      "Define Slack legal triage playbooks",
      "Enable Copilot with approved prompt libraries",
    ],
  },
  {
    id: "legal-legal-ops",
    name: "Legal Ops Stack",
    industry: "legal",
    role: "Legal operations",
    summary:
      "Clio plus Harvey for hybrid workflows, Airtable for vendor and matter analytics, Zapier automations, and Slack for routing.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Vendor management, outside counsel coordination, and KPIs.",
    team_size_fit: "Ops pods supporting distributed counsel",
    recommended_for: "Teams modernizing intake without ripping out Clio.",
    not_ideal_for: "Firms without ops bandwidth to maintain automations.",
    tools: [
      libTool("clio-manage-ai-ops", "Clio Manage AI", {
        website_url: "https://www.clio.com",
        category: "Practice management",
        role_in_stack: "Operational source of truth for matters",
        workflow_tags: ["legal_ops"],
      }),
      libTool("harvey-ops", "Harvey", {
        website_url: "https://www.harvey.ai",
        category: "Legal AI",
        role_in_stack: "Document-heavy workflows and playbooks",
        workflow_tags: ["legal_ai"],
      }),
      libTool("airtable-ops", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Ops analytics",
        role_in_stack: "Vendor scorecards and workload dashboards",
        workflow_tags: ["database"],
      }),
      libTool("zapier-ops", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Connect Clio, billing, and Slack alerts",
        workflow_tags: ["automation"],
      }),
      libTool("slackbot-ops", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Route requests to the right counsel template",
        workflow_tags: ["chat"],
      }),
    ],
    rationale:
      "Legal ops scales when matter systems stay authoritative while Harvey accelerates repetitive doc work and Airtable surfaces KPIs.",
    tradeoffs: ["Automation debt if Zapier flows are not documented."],
    setup_order: [
      "Inventory systems of record (Clio, billing, HRIS)",
      "Stand up Airtable vendor and SLA views",
      "Pilot Harvey on low-risk contract families",
    ],
  },
  {
    id: "education-teacher-prep",
    name: "Teacher Prep Stack",
    industry: "education",
    role: "K–12 / higher-ed instructor",
    summary:
      "Khanmigo for guided practice, Canva for classroom visuals, Gemini in Google Classroom/Drive, and Zoom AI Companion for live sessions.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Lesson planning, differentiation, and live teaching support.",
    team_size_fit: "Individual teachers and PLCs",
    recommended_for: "Google Classroom schools piloting AI thoughtfully.",
    not_ideal_for: "Districts blocking third-party tutoring copilots.",
    tools: [
      libTool("khanmigo", "Khanmigo", {
        website_url: "https://www.khanacademy.org",
        category: "Teaching copilot",
        role_in_stack: "Guided practice aligned to Khan content",
        workflow_tags: ["education", "ai_assistant"],
      }),
      libTool("canva-edu", "Canva (Magic Activities / Quiz Generator / Course tools)", {
        website_url: "https://www.canva.com",
        category: "Design / classroom",
        role_in_stack: "Worksheets, visuals, and quick assessments",
        workflow_tags: ["design", "education"],
      }),
      libTool("google-workspace-gemini-edu", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Docs/Slides assistance with admin controls",
        workflow_tags: ["google_workspace"],
      }),
      libTool("zoom-ai-edu", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Live captions and class recap notes",
        workflow_tags: ["video", "education"],
      }),
    ],
    rationale:
      "Teachers need safe, classroom-ready copilots plus fast visual materials; this stack keeps AI inside tools families already recognize.",
    tradeoffs: ["Requires clear policies for student data in AI features."],
    setup_order: [
      "Enable Gemini for Education controls",
      "Create Canva class templates",
      "Pilot Khanmigo on one unit",
    ],
  },
  {
    id: "education-curriculum-content",
    name: "Curriculum & Content Stack",
    industry: "education",
    role: "Instructional designer",
    summary:
      "Khanmigo for scaffolding, ChatGPT for outlines, Canva for assets, Fireflies for curriculum meetings, Gemini in Workspace for collaboration.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Unit design, rubrics, and multimedia lesson kits.",
    team_size_fit: "Curriculum teams of 3–30",
    recommended_for: "Teams building reusable course kits at pace.",
    not_ideal_for: "Highly regulated programs needing offline-only authoring.",
    tools: [
      libTool("khanmigo-curr", "Khanmigo", {
        website_url: "https://www.khanacademy.org",
        category: "Teaching copilot",
        role_in_stack: "Practice sequences tied to standards",
        workflow_tags: ["education"],
      }),
      libTool("chatgpt-business-edu", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Lesson outlines and assessment item generation",
        workflow_tags: ["ai_assistant", "writing"],
      }),
      libTool("canva-curr", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Slide decks, handouts, and video storyboards",
        workflow_tags: ["design"],
      }),
      libTool("fireflies-edu", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Capture curriculum committee decisions",
        workflow_tags: ["meetings"],
      }),
      libTool("google-workspace-gemini-curr", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Shared authoring with version history",
        workflow_tags: ["google_workspace", "documents"],
      }),
    ],
    rationale:
      "Curriculum teams iterate in meetings; pairing Fireflies with Workspace keeps decisions traceable while AI accelerates asset production.",
    tradeoffs: ["Overlapping writing assistants if prompts are not standardized."],
    setup_order: [
      "Define style guide for AI-generated items",
      "Template Canva kits per subject",
      "Pilot Fireflies on internal meetings only",
    ],
  },
  {
    id: "education-school-admin",
    name: "School Admin / Operations Stack",
    industry: "education",
    role: "Principal / operations",
    summary:
      "Gemini in Workspace for communications, Slack for staff channels, Airtable for facilities/projects, Zapier for forms, Zoom AI for community forums.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Schedules, incidents, and parent comms with light automation.",
    team_size_fit: "School or small district ops teams",
    recommended_for: "Leaders standardizing on Google Workspace.",
    not_ideal_for: "Districts entirely on Microsoft without Workspace.",
    tools: [
      libTool("google-workspace-gemini-admin", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Mail, Docs, and Sheets with admin Gemini controls",
        workflow_tags: ["google_workspace"],
      }),
      libTool("slackbot-admin", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Staff alerts and incident threads",
        workflow_tags: ["chat"],
      }),
      libTool("airtable-admin", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Operations",
        role_in_stack: "Facilities tickets, vendor rosters, PD tracking",
        workflow_tags: ["database"],
      }),
      libTool("zapier-admin", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Form submissions to Sheets/Slack",
        workflow_tags: ["automation"],
      }),
      libTool("zoom-ai-admin", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Board and parent forum summaries",
        workflow_tags: ["video"],
      }),
    ],
    rationale:
      "School operations need dependable comms plus lightweight databases; Gemini plus Airtable keeps admins out of heavyweight ERPs for daily work.",
    tradeoffs: ["Automation needs ongoing ownership as staff change."],
    setup_order: [
      "Audit Workspace OU policies for Gemini",
      "Model top five Zapier flows (forms → Sheets)",
      "Train office staff on Slack norms",
    ],
  },
];
