import type { VaultCuratedStackTemplate } from "@/lib/vault/software-library-schema";
import { libTool } from "@/lib/vault/stack-seeds/lib-tool";

/** HR / Recruiting, Product / PM, Software Dev / IT (9 archetypes). */
export const VAULT_STACK_SEEDS_BATCH_04: VaultCuratedStackTemplate[] = [
  {
    id: "hr_recruiting-hris-native",
    name: "HRIS-native Stack",
    industry: "hr_recruiting",
    role: "HRBP",
    summary: "Workday Illuminate on Workday data, Slack for employee comms, Zoom AI for hybrid forums, Gemini in Workspace for docs.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "Policy comms, manager enablement, and people analytics on HRIS.",
    team_size_fit: "Mid-market to enterprise HR",
    recommended_for: "Workday customers with Google Workspace collaboration.",
    not_ideal_for: "Teams without Workday admin partnership.",
    tools: [
      libTool("workday-illuminate", "Workday Illuminate", {
        website_url: "https://www.workday.com",
        category: "HCM + AI",
        role_in_stack: "AI assistance across Workday experiences",
        workflow_tags: ["hris", "ai_assistant"],
      }),
      libTool("slackbot-hr", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Manager nudges and ER triage rooms",
        workflow_tags: ["chat"],
      }),
      libTool("zoom-ai-hr", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "All-hands and enablement session summaries",
        workflow_tags: ["video"],
      }),
      libTool("google-workspace-gemini-hr", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Policy docs and manager guides",
        workflow_tags: ["google_workspace", "documents"],
      }),
    ],
    rationale: "HRIS-native stacks keep people data authoritative while collaboration tools stay lightweight and familiar.",
    tradeoffs: ["Requires careful change management when AI touches sensitive HR data."],
    setup_order: ["Enable Illuminate with least-privilege roles", "Publish Slack ER playbooks", "Train managers on Gemini prompts"],
  },
  {
    id: "hr_recruiting-recruiting-ops",
    name: "Recruiting Ops Stack",
    industry: "hr_recruiting",
    role: "Recruiting coordinator",
    summary: "Workday Illuminate for hiring workflows, Fireflies for interview panels, Airtable for pipeline ops, Zapier for scheduling.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "High-volume recruiting with structured feedback.",
    team_size_fit: "TA teams 5–80",
    recommended_for: "Workday Recruiting customers.",
    not_ideal_for: "Greenhouse-only shops without Workday.",
    tools: [
      libTool("workday-illuminate-rec", "Workday Illuminate", {
        website_url: "https://www.workday.com",
        category: "HCM + AI",
        role_in_stack: "Candidate summaries and recruiter assist",
        workflow_tags: ["hris", "recruiting"],
      }),
      libTool("fireflies-rec", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Panel debriefs and structured feedback",
        workflow_tags: ["meetings"],
      }),
      libTool("airtable-rec", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Recruiting ops",
        role_in_stack: "Sourcing campaigns, events, and offer tracking",
        workflow_tags: ["database", "recruiting"],
      }),
      libTool("zapier-rec", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Calendar, email, and Slack coordination",
        workflow_tags: ["automation"],
      }),
    ],
    rationale: "Recruiting ops needs fast coordination; Workday plus Airtable keeps system-of-record vs. flexible ops separated cleanly.",
    tradeoffs: ["Dual tracking if Airtable mirrors Workday without governance."],
    setup_order: ["Define which fields are authoritative in Workday", "Template Airtable for events", "Pilot Fireflies on panels only"],
  },
  {
    id: "hr_recruiting-lean-people-ops",
    name: "Lean People Ops Stack",
    industry: "hr_recruiting",
    role: "People ops generalist",
    summary: "Gemini in Workspace, Airtable for lightweight HRIS extensions, Slack for culture, Zoom AI for onboarding.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "low",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Startups without full Workday yet.",
    team_size_fit: "10–200",
    recommended_for: "Google Workspace-native startups.",
    not_ideal_for: "Regulated enterprises needing full HRIS compliance suite.",
    tools: [
      libTool("google-workspace-gemini-people", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Policies, onboarding checklists, and FAQs",
        workflow_tags: ["google_workspace"],
      }),
      libTool("airtable-people", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "People ops",
        role_in_stack: "PTO policies, equipment, and lightweight HR data",
        workflow_tags: ["database", "hr"],
      }),
      libTool("slackbot-people", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Onboarding cohort channels and polls",
        workflow_tags: ["chat"],
      }),
      libTool("zoom-ai-people", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Live onboarding session support",
        workflow_tags: ["video"],
      }),
    ],
    rationale: "Lean people teams stretch Workspace plus Airtable until HRIS maturity, with Slack as the cultural front door.",
    tradeoffs: ["Compliance gaps vs. dedicated HRIS for large orgs."],
    setup_order: ["Centralize HR FAQs in Drive", "Model Airtable employee services", "Create onboarding Slack templates"],
  },
  {
    id: "product_project_management-pm-os",
    name: "PM Operating System Stack",
    industry: "product_project_management",
    role: "Product ops / PM",
    summary: "Atlassian Rovo on Jira/Confluence, Slack for decisions, Gemini in Workspace for specs, Airtable for lightweight roadmaps.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Delivery orgs on Atlassian plus Google collaboration.",
    team_size_fit: "Product+engineering 20–500",
    recommended_for: "Teams using Jira Software + Confluence with Workspace.",
    not_ideal_for: "Linear-only shops skipping Atlassian.",
    tools: [
      libTool("atlassian-rovo", "Atlassian Rovo", {
        website_url: "https://www.atlassian.com/software/rovo",
        category: "Delivery AI",
        role_in_stack: "Search and assist across Jira and Confluence",
        workflow_tags: ["delivery", "engineering"],
      }),
      libTool("slackbot-pm", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Incident and decision threads",
        workflow_tags: ["chat"],
      }),
      libTool("google-workspace-gemini-pm", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "PRDs, interview notes, and exec updates",
        workflow_tags: ["google_workspace", "documents"],
      }),
      libTool("airtable-pm", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Planning",
        role_in_stack: "Cross-team roadmap and capacity views",
        workflow_tags: ["database", "planning"],
      }),
    ],
    rationale: "PM operating systems need authoritative delivery data (Jira) plus flexible narrative surfaces (Docs) and comms (Slack).",
    tradeoffs: ["Rovo value depends on Confluence/Jira hygiene."],
    setup_order: ["Normalize Jira project taxonomy", "Index Confluence spaces for Rovo", "Define Airtable as planning overlay only"],
  },
  {
    id: "product_project_management-briefing-spec",
    name: "Briefing & Spec Stack",
    industry: "product_project_management",
    role: "PM / designer",
    summary: "ChatGPT for structured specs, Atlassian Rovo for delivery context, Figma Make for UI exploration, Fireflies for discovery.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Discovery → spec → design exploration loops.",
    team_size_fit: "Product triads",
    recommended_for: "Teams pairing Figma with Jira for execution.",
    not_ideal_for: "Hardware programs needing MBSE tools.",
    tools: [
      libTool("chatgpt-business-spec", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "PRDs, user stories, and acceptance criteria",
        workflow_tags: ["writing", "ai_assistant"],
      }),
      libTool("atlassian-rovo-spec", "Atlassian Rovo", {
        website_url: "https://www.atlassian.com/software/rovo",
        category: "Delivery AI",
        role_in_stack: "Pull context from Jira/Confluence during drafting",
        workflow_tags: ["delivery"],
      }),
      libTool("figma-make", "Figma Make", {
        website_url: "https://www.figma.com",
        category: "Design",
        role_in_stack: "Exploratory UI and interactive prototypes",
        workflow_tags: ["design", "ux"],
      }),
      libTool("fireflies-spec", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Customer discovery transcripts",
        workflow_tags: ["meetings"],
      }),
    ],
    rationale: "Specs improve when grounded in real discovery notes and delivery context; Rovo plus Fireflies reduces re-asking.",
    tradeoffs: ["Requires discipline to link Figma files to Jira issues."],
    setup_order: ["Create ChatGPT spec templates", "Connect Rovo to canonical spaces", "Pilot Figma Make on one initiative"],
  },
  {
    id: "product_project_management-cross-functional-execution",
    name: "Cross-functional Execution Stack",
    industry: "product_project_management",
    role: "Program manager",
    summary: "Airtable for program tracking, Slack for comms, Zoom AI for steering notes, Zapier for rollups.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Cross-functional programs without heavy PPM licenses.",
    team_size_fit: "5–80",
    recommended_for: "Matrixed teams needing lightweight portfolio views.",
    not_ideal_for: "Capital projects needing Primavera-level scheduling.",
    tools: [
      libTool("airtable-prog", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Program management",
        role_in_stack: "Milestones, RAID logs, and dependencies",
        workflow_tags: ["database", "planning"],
      }),
      libTool("slackbot-prog", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Steerco channels and decision logs",
        workflow_tags: ["chat"],
      }),
      libTool("zoom-ai-prog", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Steerco summaries and actions",
        workflow_tags: ["video", "meetings"],
      }),
      libTool("zapier-prog", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Status rollups to email/Slack",
        workflow_tags: ["automation"],
      }),
    ],
    rationale: "Cross-functional execution needs a single flexible tracker plus reliable meeting memory and light automation.",
    tradeoffs: ["Airtable can sprawl without program office governance."],
    setup_order: ["Define program taxonomy in Airtable", "Create Slack steerco template", "Automate weekly rollup via Zapier"],
  },
  {
    id: "software_dev_it-developer-core",
    name: "Developer Core Stack",
    industry: "software_dev_it",
    role: "Engineering lead",
    summary: "GitHub Copilot in the IDE, ChatGPT for design spikes, Slack for incidents, Atlassian Rovo across Jira/Confluence.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Modern SDLC with AI-assisted coding and delivery context.",
    team_size_fit: "Engineering orgs 10–500",
    recommended_for: "GitHub + Jira shops.",
    not_ideal_for: "GitLab-only teams without GitHub Copilot path.",
    tools: [
      libTool("github-copilot", "GitHub Copilot", {
        website_url: "https://github.com/features/copilot",
        category: "Developer AI",
        role_in_stack: "Inline code completion and chat in IDE",
        workflow_tags: ["engineering", "ai_assistant"],
      }),
      libTool("chatgpt-business-dev", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Architecture spikes and test ideas",
        workflow_tags: ["ai_assistant"],
      }),
      libTool("slackbot-dev", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Incidents, deploy announcements, and triage",
        workflow_tags: ["chat", "engineering"],
      }),
      libTool("atlassian-rovo-dev", "Atlassian Rovo", {
        website_url: "https://www.atlassian.com/software/rovo",
        category: "Delivery AI",
        role_in_stack: "Search across Jira/Confluence for engineers",
        workflow_tags: ["delivery"],
      }),
    ],
    rationale: "Developer cores pair IDE-native copilots with delivery memory in Jira/Confluence and fast incident comms in Slack.",
    tradeoffs: ["Multiple AI assistants if ChatGPT duplicates Copilot chat—set boundaries."],
    setup_order: ["Enable Copilot Business policies", "Index canonical Confluence spaces", "Define Slack incident roles"],
  },
  {
    id: "software_dev_it-internal-tools",
    name: "Internal Tools Stack",
    industry: "software_dev_it",
    role: "Internal platform engineer",
    summary: "GitHub Copilot for services, Airtable for ops data, Zapier for integrations, Figma Make for admin UX.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Internal apps and admin consoles with pragmatic glue.",
    team_size_fit: "Platform teams 3–40",
    recommended_for: "Teams shipping internal CRUD apps quickly.",
    not_ideal_for: "Mission-critical regulated systems without SDLC rigor.",
    tools: [
      libTool("github-copilot-internal", "GitHub Copilot", {
        website_url: "https://github.com/features/copilot",
        category: "Developer AI",
        role_in_stack: "Accelerate internal service code",
        workflow_tags: ["engineering"],
      }),
      libTool("airtable-internal", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Ops data",
        role_in_stack: "Feature flags, access requests, and catalogs",
        workflow_tags: ["database"],
      }),
      libTool("zapier-internal", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Glue between SaaS admin APIs",
        workflow_tags: ["automation"],
      }),
      libTool("figma-make-internal", "Figma Make", {
        website_url: "https://www.figma.com",
        category: "Design",
        role_in_stack: "Admin UX explorations",
        workflow_tags: ["design", "ux"],
      }),
    ],
    rationale: "Internal tools succeed when engineers ship fast with copilots while ops data stays approachable in Airtable.",
    tradeoffs: ["Airtable is not a transactional database for hot paths."],
    setup_order: ["Define internal UX kit in Figma", "Model access request flow in Airtable", "Wrap risky APIs behind review"],
  },
  {
    id: "software_dev_it-it-automation",
    name: "IT Automation Stack",
    industry: "software_dev_it",
    role: "IT manager",
    summary: "Zapier for SaaS glue, Slack for employee comms, Atlassian Rovo for ITSM knowledge, Gemini in Workspace for policies.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Employee onboarding/offboarding and SaaS administration.",
    team_size_fit: "IT teams 3–60",
    recommended_for: "Google Workspace + Jira Service Management style ops.",
    not_ideal_for: "Legacy ITSM without Jira adoption.",
    tools: [
      libTool("zapier-it", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Lifecycle hooks across HRIS and SaaS admin",
        workflow_tags: ["automation"],
      }),
      libTool("slackbot-it", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Employee self-service and IT announcements",
        workflow_tags: ["chat", "support"],
      }),
      libTool("atlassian-rovo-it", "Atlassian Rovo", {
        website_url: "https://www.atlassian.com/software/rovo",
        category: "Delivery AI",
        role_in_stack: "Search across ITSM articles and tickets",
        workflow_tags: ["support", "delivery"],
      }),
      libTool("google-workspace-gemini-it", "Google Workspace with Gemini", {
        website_url: "https://workspace.google.com",
        category: "Productivity suite",
        role_in_stack: "Policy docs and device setup guides",
        workflow_tags: ["google_workspace", "documents"],
      }),
    ],
    rationale: "IT automation shines when employee-facing comms (Slack) pair with searchable ITSM context (Rovo) and pragmatic SaaS glue (Zapier).",
    tradeoffs: ["Zapier maintenance burden as SaaS APIs change."],
    setup_order: ["Inventory SaaS admin APIs", "Publish IT knowledge in Confluence", "Automate onboarding checklist via Zapier"],
  },
];
