import type { VaultCuratedStackTemplate } from "@/lib/vault/software-library-schema";
import { libTool } from "@/lib/vault/stack-seeds/lib-tool";

/** Consulting / Professional Services, Music, Art / Design (9 archetypes). */
export const VAULT_STACK_SEEDS_BATCH_06: VaultCuratedStackTemplate[] = [
  {
    id: "consulting_professional_services-research-deck",
    name: "Research & Deck Stack",
    industry: "consulting_professional_services",
    role: "Associate / manager",
    summary: "ChatGPT for structured arguments, Perplexity for cited research, Microsoft 365 Copilot for client-ready decks, Canva for visuals.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Client-ready outputs with Microsoft-native polish.",
    team_size_fit: "Consulting teams 5–500",
    recommended_for: "Microsoft 365 firms needing fast research-to-slide cycles.",
    not_ideal_for: "Google-only firms without Copilot path.",
    tools: [
      libTool("chatgpt-business-cons", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Issue trees, storylines, and executive summaries",
        workflow_tags: ["writing", "ai_assistant"],
      }),
      libTool("perplexity-cons", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Cited market, policy, and competitor pulls",
        workflow_tags: ["research"],
      }),
      libTool("ms365-copilot-cons", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "PowerPoint and Word drafting with firm templates",
        workflow_tags: ["copilot", "documents"],
      }),
      libTool("canva-cons", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Client one-pagers and workshop boards",
        workflow_tags: ["design"],
      }),
    ],
    rationale: "Consulting deliverables need defensible research plus slide-native copilots; Canva accelerates workshop visuals.",
    tradeoffs: ["Still requires partner review for client confidentiality."],
    setup_order: ["Publish firm prompt and template libraries", "Train Perplexity sourcing standards", "Lock Canva brand kits"],
  },
  {
    id: "consulting_professional_services-delivery-ops",
    name: "Delivery Ops Stack",
    industry: "consulting_professional_services",
    role: "Engagement manager",
    summary: "Airtable for staffing and RAID logs, Zapier for lightweight integrations, Slack for war rooms, Fireflies for client workshops.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Engagement delivery mechanics separate from client IP storage.",
    team_size_fit: "PMO / resourcing pods",
    recommended_for: "Boutiques scaling engagements without heavy PSA yet.",
    not_ideal_for: "Firms requiring full PSA + finance integration day one.",
    tools: [
      libTool("airtable-del", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Engagement ops",
        role_in_stack: "Staffing, RAID, and deliverable trackers",
        workflow_tags: ["database", "planning"],
      }),
      libTool("zapier-del", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Time entry reminders and CRM nudges",
        workflow_tags: ["automation"],
      }),
      libTool("slackbot-del", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Engagement rooms and escalation paths",
        workflow_tags: ["chat"],
      }),
      libTool("fireflies-del", "Fireflies", {
        website_url: "https://fireflies.ai",
        category: "Meeting notes",
        role_in_stack: "Workshop decisions and action tracking",
        workflow_tags: ["meetings"],
      }),
    ],
    rationale: "Delivery ops needs flexible trackers plus reliable meeting memory; keep client IP in approved repositories outside Airtable if required.",
    tradeoffs: ["Airtable not a substitute for secured client document vaults."],
    setup_order: ["Define data classes allowed in Airtable", "Template engagement Slack channels", "Pilot Fireflies on internal workshops"],
  },
  {
    id: "consulting_professional_services-knowledge-advisory",
    name: "Knowledge-heavy Advisory Stack",
    industry: "consulting_professional_services",
    role: "Expert partner",
    summary: "Atlassian Rovo across Confluence/Jira knowledge, Perplexity for external research, Microsoft 365 Copilot for memos, Zoom AI for expert calls.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "Firms with strong internal knowledge bases plus external research needs.",
    team_size_fit: "Advisory practices 20–2000",
    recommended_for: "Atlassian + Microsoft advisory firms.",
    not_ideal_for: "Firms without maintained Confluence knowledge.",
    tools: [
      libTool("atlassian-rovo-cons", "Atlassian Rovo", {
        website_url: "https://www.atlassian.com/software/rovo",
        category: "Delivery AI",
        role_in_stack: "Search and synthesis across internal knowledge",
        workflow_tags: ["documentation", "delivery"],
      }),
      libTool("perplexity-adv", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "External cited research complementing internal IP",
        workflow_tags: ["research"],
      }),
      libTool("ms365-copilot-adv", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "Client memos and governance-friendly drafting",
        workflow_tags: ["copilot"],
      }),
      libTool("zoom-ai-adv", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Expert interview summaries",
        workflow_tags: ["video", "meetings"],
      }),
    ],
    rationale: "Knowledge-heavy advisory combines internal retrieval (Rovo) with external citations (Perplexity) and Microsoft-grade client outputs.",
    tradeoffs: ["Requires ongoing curation of Confluence spaces to keep Rovo trustworthy."],
    setup_order: ["Archive stale pages before Rovo rollout", "Define client vs internal prompt policies", "Train experts on Perplexity sourcing"],
  },
  {
    id: "music-song-ideation",
    name: "Song Ideation Stack",
    industry: "music",
    role: "Songwriter / producer",
    summary: "Suno for melodic ideas, AIVA for arrangement seeds, ChatGPT for lyric structure and prompts.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "low",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Fast ideation loops before DAW production.",
    team_size_fit: "Independent artists",
    recommended_for: "Creators exploring hooks quickly.",
    not_ideal_for: "Final mastering pipeline (use dedicated audio tools).",
    tools: [
      libTool("suno", "Suno", {
        website_url: "https://suno.ai",
        category: "Generative music",
        role_in_stack: "Sketch songs and stems from prompts",
        workflow_tags: ["music", "ai_media"],
      }),
      libTool("aiva", "AIVA", {
        website_url: "https://www.aiva.ai",
        category: "Composition AI",
        role_in_stack: "Orchestral scaffolding and harmonic ideas",
        workflow_tags: ["music", "ai_media"],
      }),
      libTool("chatgpt-business-music", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Lyric frameworks and prompt iteration",
        workflow_tags: ["writing", "ai_assistant"],
      }),
    ],
    rationale: "Song ideation benefits from parallel generative tools plus a language model for lyrical scaffolding.",
    tradeoffs: ["Rights and distribution rules vary by platform—verify before release."],
    setup_order: ["Document rights workflow", "Create prompt libraries for Suno/AIVA", "Export stems to DAW for finishing"],
  },
  {
    id: "music-production-polish",
    name: "Production Polish Stack",
    industry: "music",
    role: "Indie producer",
    summary: "LANDR for mastering assist, Suno for ideas, AIVA for arrangement, ChatGPT for release notes.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "From rough mix toward release-ready polish.",
    team_size_fit: "Home studios",
    recommended_for: "Independent releases without big-studio budgets.",
    not_ideal_for: "High-stakes mastering needing dedicated engineer-only workflow.",
    tools: [
      libTool("landr", "LANDR", {
        website_url: "https://www.landr.com",
        category: "Mastering",
        role_in_stack: "AI-assisted mastering and distribution hooks",
        workflow_tags: ["music", "audio"],
      }),
      libTool("suno-polish", "Suno", {
        website_url: "https://suno.ai",
        category: "Generative music",
        role_in_stack: "Fill harmonic gaps or backing ideas",
        workflow_tags: ["music"],
      }),
      libTool("aiva-polish", "AIVA", {
        website_url: "https://www.aiva.ai",
        category: "Composition AI",
        role_in_stack: "Additional instrumentation layers",
        workflow_tags: ["music"],
      }),
      libTool("chatgpt-business-polish", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Release copy and pitch emails",
        workflow_tags: ["writing"],
      }),
    ],
    rationale: "Production polish stacks pair generative ideation with mastering assistance and marketing copy in one loop.",
    tradeoffs: ["AI mastering is a taste choice—always A/B with references."],
    setup_order: ["Calibrate LANDR reference tracks", "Define stem export discipline", "Template release notes in ChatGPT"],
  },
  {
    id: "music-music-marketing",
    name: "Music Marketing Stack",
    industry: "music",
    role: "Indie marketer",
    summary: "LANDR distribution hooks, Canva for social creatives, ChatGPT for bios and pitches, Runway for short promo clips.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Release week content bursts across channels.",
    team_size_fit: "Solo to small label",
    recommended_for: "Artists self-releasing with high social cadence.",
    not_ideal_for: "Teams without short-form video appetite.",
    tools: [
      libTool("landr-mkt", "LANDR", {
        website_url: "https://www.landr.com",
        category: "Distribution",
        role_in_stack: "Distribution and mastering adjacent workflows",
        workflow_tags: ["music", "marketing"],
      }),
      libTool("canva-music", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Drop announcements, stories, and lyric cards",
        workflow_tags: ["design", "marketing"],
      }),
      libTool("chatgpt-business-music-mkt", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Pitch emails, playlist pitches, and bios",
        workflow_tags: ["writing"],
      }),
      libTool("runway-music", "Runway", {
        website_url: "https://runwayml.com",
        category: "Generative video",
        role_in_stack: "Short promo visuals and teasers",
        workflow_tags: ["video", "ai_media"],
      }),
    ],
    rationale: "Music marketing needs distribution adjacent tools plus creative throughput for social and promo video.",
    tradeoffs: ["Short-form cadence can fatigue audiences—plan rest weeks."],
    setup_order: ["Lock release calendar", "Batch Canva templates per single", "Create Runway style presets"],
  },
  {
    id: "art_design-brand-design",
    name: "Brand Design Stack",
    industry: "art_design",
    role: "Brand designer",
    summary: "Adobe Firefly for generative brand imagery, Canva Magic Studio for social kits, Figma Make for UI exploration, ChatGPT for naming lines.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Brand systems with regulated generative assets plus UI exploration.",
    team_size_fit: "Studio pods 3–40",
    recommended_for: "Teams with Adobe admin and Figma org.",
    not_ideal_for: "Print-only shops without digital brand governance.",
    tools: [
      libTool("adobe-firefly-brand-d", "Adobe Firefly", {
        website_url: "https://www.adobe.com/products/firefly.html",
        category: "Generative design",
        role_in_stack: "Brand-trained imagery with enterprise controls",
        workflow_tags: ["design", "ai_media"],
      }),
      libTool("canva-magic-brand-d", "Canva Magic Studio", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Social templates and campaign variants",
        workflow_tags: ["design", "marketing"],
      }),
      libTool("figma-make-brand", "Figma Make", {
        website_url: "https://www.figma.com",
        category: "Design",
        role_in_stack: "Product UI explorations tied to brand",
        workflow_tags: ["design", "ux"],
      }),
      libTool("chatgpt-business-brand-d", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Microcopy, naming explorations, and creative briefs",
        workflow_tags: ["writing"],
      }),
    ],
    rationale: "Brand design stacks pair governed generative imagery with high-velocity Canva outputs and Figma-native UI craft.",
    tradeoffs: ["Overlapping generative tools need clear ownership per asset type."],
    setup_order: ["Sync brand kit across Firefly and Canva", "Define Figma libraries as source of truth for UI", "Publish ChatGPT naming rubric"],
  },
  {
    id: "art_design-concept-art",
    name: "Concept Art Stack",
    industry: "art_design",
    role: "Concept artist",
    summary: "Adobe Firefly for explorations, Runway for motion concepts, Figma Make for structured exploration boards.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Rapid visual exploration before production art passes.",
    team_size_fit: "Game/film pre-production pods",
    recommended_for: "Studios comfortable with generative pre-vis.",
    not_ideal_for: "Final pixel production without artist finishing pass.",
    tools: [
      libTool("adobe-firefly-concept", "Adobe Firefly", {
        website_url: "https://www.adobe.com/products/firefly.html",
        category: "Generative design",
        role_in_stack: "Explorations with brand/model controls",
        workflow_tags: ["design", "ai_media"],
      }),
      libTool("runway-concept", "Runway", {
        website_url: "https://runwayml.com",
        category: "Generative video",
        role_in_stack: "Motion concepting and shot tests",
        workflow_tags: ["video", "ai_media"],
      }),
      libTool("figma-make-concept", "Figma Make", {
        website_url: "https://www.figma.com",
        category: "Design",
        role_in_stack: "Boards linking references, notes, and iterations",
        workflow_tags: ["design", "ux"],
      }),
    ],
    rationale: "Concept art workflows benefit when still explorations (Firefly/Runway) feed structured boards in Figma for review.",
    tradeoffs: ["Generative outputs need director sign-off before becoming canon."],
    setup_order: ["Create Figma review template", "Define Firefly style references", "Shortlist Runway prompts per sequence"],
  },
  {
    id: "art_design-social-design",
    name: "Social Design Stack",
    industry: "art_design",
    role: "Social designer",
    summary: "Canva for volume, Adobe Firefly for brand imagery, HubSpot Breeze for campaign alignment, ChatGPT for captions.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "High-cadence social with CRM-aware campaigns.",
    team_size_fit: "Marketing design pods",
    recommended_for: "HubSpot-driven social teams.",
    not_ideal_for: "Organic-only brands avoiding CRM tooling.",
    tools: [
      libTool("canva-social", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Daily social formats and animations",
        workflow_tags: ["design", "marketing"],
      }),
      libTool("adobe-firefly-social", "Adobe Firefly", {
        website_url: "https://www.adobe.com/products/firefly.html",
        category: "Generative design",
        role_in_stack: "Brand hero stills for campaigns",
        workflow_tags: ["ai_media", "design"],
      }),
      libTool("hubspot-breeze-social", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Campaign suggestions tied to segments",
        workflow_tags: ["crm", "marketing"],
      }),
      libTool("chatgpt-business-social", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Caption variants and A/B hooks",
        workflow_tags: ["writing"],
      }),
    ],
    rationale: "Social design at scale pairs Canva throughput with Firefly brand imagery and HubSpot-aware messaging suggestions.",
    tradeoffs: ["Caption AI still needs brand compliance review."],
    setup_order: ["Sync HubSpot segments to Canva campaigns", "Train Firefly brand model", "Publish ChatGPT banned phrases list"],
  },
];
