import type { VaultCuratedStackTemplate } from "@/lib/vault/software-library-schema";
import { libTool } from "@/lib/vault/stack-seeds/lib-tool";

/** Ecommerce / Retail, Real Estate, Healthcare / Clinics (9 archetypes). */
export const VAULT_STACK_SEEDS_BATCH_05: VaultCuratedStackTemplate[] = [
  {
    id: "ecommerce_retail-shopify-native",
    name: "Shopify-native Stack",
    industry: "ecommerce_retail",
    role: "DTC founder",
    summary: "Shopify Sidekick and Magic for storefront ops, Canva for creative, ChatGPT for merchandising copy.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Shopify-first brands scaling SKU and content velocity.",
    team_size_fit: "1–50",
    recommended_for: "Shopify merchants wanting AI inside admin.",
    not_ideal_for: "Headless commerce stacks without Shopify admin.",
    tools: [
      libTool("shopify-sidekick", "Shopify Sidekick", {
        website_url: "https://www.shopify.com",
        category: "Commerce AI",
        role_in_stack: "Admin assistance for merchandising tasks",
        workflow_tags: ["ecommerce", "ai_assistant"],
      }),
      libTool("shopify-magic", "Shopify Magic", {
        website_url: "https://www.shopify.com",
        category: "Commerce AI",
        role_in_stack: "Product descriptions and email suggestions",
        workflow_tags: ["ecommerce", "writing"],
      }),
      libTool("canva-shop", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Ads, email headers, and social drops",
        workflow_tags: ["design", "marketing"],
      }),
      libTool("chatgpt-business-shop", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "Campaign angles and customer email drafts",
        workflow_tags: ["writing"],
      }),
    ],
    rationale: "Shopify-native merchants move fastest when AI sits inside admin for catalog work while Canva handles creative throughput.",
    tradeoffs: ["Creative quality still needs brand review."],
    setup_order: ["Enable Sidekick permissions", "Template Canva ad sizes per channel", "Define ChatGPT tone for brand"],
  },
  {
    id: "ecommerce_retail-growth-ecommerce",
    name: "Growth Ecommerce Stack",
    industry: "ecommerce_retail",
    role: "Growth lead",
    summary: "Shopify Sidekick plus HubSpot Breeze for CRM loops, Canva for creative, Intercom Fin for shopper support.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "DTC brands connecting storefront, CRM, and support.",
    team_size_fit: "10–120",
    recommended_for: "Shopify + HubSpot growth teams.",
    not_ideal_for: "Marketplace-only sellers without owned CRM.",
    tools: [
      libTool("shopify-sidekick-gr", "Shopify Sidekick", {
        website_url: "https://www.shopify.com",
        category: "Commerce AI",
        role_in_stack: "Merchandising and ops assistance",
        workflow_tags: ["ecommerce"],
      }),
      libTool("hubspot-breeze-ec", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Lifecycle emails and segmentation",
        workflow_tags: ["crm", "marketing"],
      }),
      libTool("canva-ec", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Campaign creative at velocity",
        workflow_tags: ["design"],
      }),
      libTool("intercom-fin-ec", "Intercom Fin", {
        website_url: "https://www.intercom.com",
        category: "Support AI",
        role_in_stack: "AI answers for shoppers on site",
        workflow_tags: ["support", "ecommerce"],
      }),
    ],
    rationale: "Growth ecommerce needs tight loops between store admin, CRM journeys, and on-site support without adding headcount linearly.",
    tradeoffs: ["Requires clean product data for Fin to answer accurately."],
    setup_order: ["Sync Shopify customers to HubSpot", "Seed Fin with policies/returns", "Template Canva campaign kits"],
  },
  {
    id: "ecommerce_retail-merchandising-ops",
    name: "Merchandising & Ops Stack",
    industry: "ecommerce_retail",
    role: "Merch / ops manager",
    summary: "Shopify Sidekick for catalog work, Airtable for assortment planning, Zapier for vendor data, Perplexity for market scans.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "standard",
    workflow_fit: "Assortment planning with light automation and research.",
    team_size_fit: "Merch teams 5–60",
    recommended_for: "Retail ops teams blending planning spreadsheets with Shopify truth.",
    not_ideal_for: "Pure wholesale without DTC channel.",
    tools: [
      libTool("shopify-sidekick-ops", "Shopify Sidekick", {
        website_url: "https://www.shopify.com",
        category: "Commerce AI",
        role_in_stack: "Bulk merchandising assistance",
        workflow_tags: ["ecommerce"],
      }),
      libTool("airtable-merch", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Planning",
        role_in_stack: "Assortment, margin ladders, and vendor scorecards",
        workflow_tags: ["database", "retail"],
      }),
      libTool("zapier-merch", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "Vendor spreadsheets → Airtable/Shopify",
        workflow_tags: ["automation"],
      }),
      libTool("perplexity-merch", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Competitive pricing and trend scans",
        workflow_tags: ["research"],
      }),
    ],
    rationale: "Merch ops needs a flexible planning surface with Shopify as execution layer and research that stays cited.",
    tradeoffs: ["Assortment truth can drift if Airtable not reconciled to ERP."],
    setup_order: ["Define canonical SKU keys", "Model assortment views in Airtable", "Automate vendor ingest via Zapier"],
  },
  {
    id: "real_estate-lead-gen",
    name: "Lead Gen Stack",
    industry: "real_estate",
    role: "Broker / growth",
    summary: "HubSpot Breeze for CRM nurture, Intercom Fin for web chat, Canva for listing creatives, Zoom AI for virtual tours.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "Inbound buyer/seller capture with polished follow-up.",
    team_size_fit: "Boutique brokerages 5–80",
    recommended_for: "HubSpot CRM real estate teams.",
    not_ideal_for: "MLS-only workflows without owned site chat.",
    tools: [
      libTool("hubspot-breeze-re", "HubSpot Breeze", {
        website_url: "https://www.hubspot.com/products/artificial-intelligence",
        category: "CRM + AI",
        role_in_stack: "Sequences and lead scoring assist",
        workflow_tags: ["crm", "sales"],
      }),
      libTool("intercom-fin-re", "Intercom Fin", {
        website_url: "https://www.intercom.com",
        category: "Support AI",
        role_in_stack: "Website visitor qualification",
        workflow_tags: ["support", "marketing"],
      }),
      libTool("canva-re", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Listing flyers, social, and open-house kits",
        workflow_tags: ["design", "real_estate"],
      }),
      libTool("zoom-ai-re", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Virtual showing summaries and next steps",
        workflow_tags: ["video"],
      }),
    ],
    rationale: "Real estate lead gen converts when chat qualifies visitors, CRM nurtures automatically, and visuals stay on-brand in Canva.",
    tradeoffs: ["Compliance with fair housing requires careful Fin prompts."],
    setup_order: ["Train Fin on approved scripts", "Segment HubSpot by buyer/seller", "Template Canva listing kits"],
  },
  {
    id: "real_estate-listing-content",
    name: "Listing Content Stack",
    industry: "real_estate",
    role: "Listing coordinator",
    summary: "Canva for marketing kits, Adobe Firefly for brand imagery, ChatGPT for descriptions, Perplexity for neighborhood research.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "easy",
    privacy_level: "standard",
    workflow_fit: "High-quality listing packages at speed.",
    team_size_fit: "Listing teams 2–40",
    recommended_for: "Brokerages investing in differentiated listing marketing.",
    not_ideal_for: "Teams without brand governance for generative imagery.",
    tools: [
      libTool("canva-listing", "Canva", {
        website_url: "https://www.canva.com",
        category: "Design",
        role_in_stack: "Listing decks, reels, and print sheets",
        workflow_tags: ["design", "real_estate"],
      }),
      libTool("adobe-firefly-listing", "Adobe Firefly", {
        website_url: "https://www.adobe.com/products/firefly.html",
        category: "Generative design",
        role_in_stack: "Hero imagery with brand controls",
        workflow_tags: ["ai_media", "design"],
      }),
      libTool("chatgpt-business-listing", "ChatGPT Business", {
        website_url: "https://chatgpt.com",
        category: "AI assistant",
        role_in_stack: "MLS-friendly descriptions and email teasers",
        workflow_tags: ["writing"],
      }),
      libTool("perplexity-listing", "Perplexity Enterprise Pro", {
        website_url: "https://www.perplexity.ai",
        category: "Research",
        role_in_stack: "Schools, transit, and comps research with citations",
        workflow_tags: ["research"],
      }),
    ],
    rationale: "Listing content wins on speed plus accuracy; Perplexity grounds neighborhood claims while Canva/Firefly handle visuals.",
    tradeoffs: ["Verify all generative claims against MLS rules."],
    setup_order: ["Publish MLS copy checklist", "Sync brand kit to Firefly", "Train coordinators on Perplexity prompts"],
  },
  {
    id: "real_estate-brokerage-ops",
    name: "Brokerage Ops Stack",
    industry: "real_estate",
    role: "Ops director",
    summary: "Airtable for transactions and vendors, Zapier for MLS handoffs, Slack for agent coordination, Zoom AI for compliance trainings.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "medium",
    setup_difficulty: "moderate",
    privacy_level: "elevated",
    workflow_fit: "Back-office visibility across agents and vendors.",
    team_size_fit: "20–300 agent brokerages",
    recommended_for: "Ops-led brokerages modernizing spreadsheets.",
    not_ideal_for: "Single-agent shops without ops overhead.",
    tools: [
      libTool("airtable-broker", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Operations",
        role_in_stack: "Transactions, vendors, and compliance tasks",
        workflow_tags: ["database", "real_estate"],
      }),
      libTool("zapier-broker", "Zapier", {
        website_url: "https://zapier.com",
        category: "Automation",
        role_in_stack: "MLS → CRM → Slack notifications",
        workflow_tags: ["automation"],
      }),
      libTool("slackbot-broker", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Deal rooms and doc requests",
        workflow_tags: ["chat"],
      }),
      libTool("zoom-ai-broker", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Meetings",
        role_in_stack: "Training summaries and policy acknowledgements",
        workflow_tags: ["video"],
      }),
    ],
    rationale: "Brokerage ops needs a flexible system of work (Airtable) with reliable notifications (Slack/Zapier) and training memory (Zoom).",
    tradeoffs: ["Airtable is not a wire instruction substitute for escrow partners."],
    setup_order: ["Model transaction stages", "Wire MLS triggers carefully", "Create Slack compliance channels"],
  },
  {
    id: "healthcare_clinics-clinical-documentation",
    name: "Clinical Documentation Stack",
    industry: "healthcare_clinics",
    role: "Clinician",
    summary: "Microsoft Dragon Copilot for clinical speech, Microsoft 365 Copilot for admin, Zoom AI Companion for telehealth sessions.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "Ambulatory clinics on Microsoft stack reducing documentation burden.",
    team_size_fit: "Small clinics to multi-site groups",
    recommended_for: "Microsoft-centric healthcare organizations.",
    not_ideal_for: "Organizations without HIPAA BAA coverage for chosen tools.",
    tools: [
      libTool("microsoft-dragon-copilot", "Microsoft Dragon Copilot", {
        website_url: "https://learn.microsoft.com/en-us/industry/healthcare/dragon-copilot",
        category: "Clinical AI",
        role_in_stack: "Ambient documentation integrated with clinical workflows",
        workflow_tags: ["healthcare", "ai_assistant"],
      }),
      libTool("ms365-copilot-health", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "Referral letters and admin correspondence",
        workflow_tags: ["copilot", "healthcare"],
      }),
      libTool("zoom-ai-health", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Telehealth",
        role_in_stack: "Session summaries for care team follow-up",
        workflow_tags: ["video", "healthcare"],
      }),
    ],
    rationale: "Clinical documentation stacks must pair ambient capture with governed Microsoft surfaces for PHI-aware workflows.",
    tradeoffs: ["Requires rigorous compliance review before go-live."],
    setup_order: ["Execute BAAs and data maps", "Pilot Dragon Copilot on limited specialties", "Train on Copilot prompt policies"],
  },
  {
    id: "healthcare_clinics-clinic-admin",
    name: "Clinic Admin Stack",
    industry: "healthcare_clinics",
    role: "Practice manager",
    summary: "Dragon Copilot for clinical notes, Airtable for lightweight ops, Zoom AI for telehealth, Slack for staff coordination.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "high",
    setup_difficulty: "moderate",
    privacy_level: "strict_compliance",
    workflow_fit: "Clinic operations adjacent to clinical documentation.",
    team_size_fit: "10–200 staff clinics",
    recommended_for: "Clinics needing ops visibility without a full ERP day one.",
    not_ideal_for: "Hospitals requiring enterprise scheduling depth only in Epic.",
    tools: [
      libTool("microsoft-dragon-copilot-admin", "Microsoft Dragon Copilot", {
        website_url: "https://learn.microsoft.com/en-us/industry/healthcare/dragon-copilot",
        category: "Clinical AI",
        role_in_stack: "Documentation acceleration at point of care",
        workflow_tags: ["healthcare"],
      }),
      libTool("airtable-clinic", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Clinic ops",
        role_in_stack: "Supplies, credentialing trackers, and projects",
        workflow_tags: ["database", "healthcare"],
      }),
      libTool("zoom-ai-clinic", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Telehealth",
        role_in_stack: "Telehealth session support",
        workflow_tags: ["video", "healthcare"],
      }),
      libTool("slackbot-clinic", "Slackbot", {
        website_url: "https://slack.com",
        category: "Collaboration",
        role_in_stack: "Staff coordination (non-PHI channels)",
        workflow_tags: ["chat"],
      }),
    ],
    rationale: "Clinic admin pairs clinical AI with lightweight ops databases while keeping PHI out of general Slack channels.",
    tradeoffs: ["Slack must be configured for non-PHI operational chatter only."],
    setup_order: ["Define PHI boundaries per tool", "Model credentialing in Airtable", "Train staff on Zoom workflows"],
  },
  {
    id: "healthcare_clinics-patient-communication",
    name: "Patient Communication Stack",
    industry: "healthcare_clinics",
    role: "Patient access lead",
    summary: "Salesforce Agentforce for journeys, Microsoft 365 Copilot for correspondence, Airtable for campaigns, Zoom AI for webinars.",
    estimated_monthly_cost_usd: null,
    estimated_cost_tier: "enterprise",
    setup_difficulty: "advanced",
    privacy_level: "strict_compliance",
    workflow_fit: "Patient outreach and access programs with CRM governance.",
    team_size_fit: "Health systems with Salesforce Health Cloud patterns",
    recommended_for: "Microsoft + Salesforce hybrid healthcare marketers.",
    not_ideal_for: "Clinics without CRM program maturity.",
    tools: [
      libTool("salesforce-agentforce-health", "Salesforce Agentforce", {
        website_url: "https://www.salesforce.com/agentforce",
        category: "CRM + AI",
        role_in_stack: "Patient journey assistance on CRM data",
        workflow_tags: ["crm", "healthcare"],
      }),
      libTool("ms365-copilot-patient", "Microsoft 365 Copilot", {
        website_url: "https://www.microsoft.com/microsoft-365/microsoft-copilot",
        category: "Productivity AI",
        role_in_stack: "Approved correspondence drafting",
        workflow_tags: ["copilot", "healthcare"],
      }),
      libTool("airtable-patient", "Airtable", {
        website_url: "https://www.airtable.com",
        category: "Campaign ops",
        role_in_stack: "Community event logistics and follow-ups",
        workflow_tags: ["database", "marketing"],
      }),
      libTool("zoom-ai-patient", "Zoom AI Companion", {
        website_url: "https://www.zoom.com",
        category: "Webinars",
        role_in_stack: "Education session summaries",
        workflow_tags: ["video", "healthcare"],
      }),
    ],
    rationale: "Patient communication needs CRM-grounded journeys plus Microsoft-governed drafting and structured ops tracking.",
    tradeoffs: ["Requires legal/marketing alignment on PHI in CRM fields."],
    setup_order: ["Data-map PHI fields in Salesforce", "Deploy Copilot with approved templates", "Use Airtable for non-PHI logistics only"],
  },
];
